/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.NHANVIEN_BUS;
import BUS.PHIEUDATTRUOC_BUS;
import BUS.PHIEUNHANPHONG_BUS;
import Class.NHANVIEN_TT;
import static GUI.QuanLyThongTinDatTruoc.showListPhieuDatTruoc;
import static GUI.QuanLyThongTinNhanPhong.showListPhieuNhanPhong;
import DTO.LOAIPHONG;
import DTO.PHIEUNHANPHONG;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author HP
 */
public class CapNhatPhieuNhanPhong extends javax.swing.JFrame {

    /**
     * Creates new form CapNhatPhieuNhanPhong
     */
    public CapNhatPhieuNhanPhong() {
        initComponents();
    }
    
    public CapNhatPhieuNhanPhong(PHIEUNHANPHONG pnp){
        initComponents();
        try{
            java.util.Date date = new SimpleDateFormat("dd-MM-yyyy").parse(pnp.getNGAYDEN()); 
            jngayden.setDate(date);
            date = new SimpleDateFormat("dd-MM-yyyy").parse(pnp.getNGAYROI());
            jngayroi.setDate(date);
        }catch(Exception e){
            e.printStackTrace();
        }
        NHANVIEN_BUS nhanvien = new NHANVIEN_BUS();
        String ten = nhanvien.getTenNhanVien(pnp.getMANV());
        NHANVIEN_TT nv = new NHANVIEN_TT(pnp.getMANV(),ten);
        jmanv.getModel().setSelectedItem(nv);
        jsonguoidikem.getModel().setSelectedItem(String.valueOf(pnp.getSONGUOIDIKEM()));
        jtfmaphieu.setText(String.valueOf(pnp.getMAPHIEUNHAN()));
        jtfmakh.setText(String.valueOf(pnp.getMAKH()));
        PHIEUNHANPHONG_BUS np = new PHIEUNHANPHONG_BUS();
        LOAIPHONG lp = np.getTTLoaiPhong(pnp.getMAPHONG());
        jloaiphong.getModel().setSelectedItem(lp);
        jphong.getModel().setSelectedItem(String.valueOf(pnp.getMAPHONG()));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jngayroi = new com.toedter.calendar.JDateChooser();
        jbsua = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbhuy = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jsonguoidikem = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jloaiphong = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jphong = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtfmaphieu = new javax.swing.JTextField();
        jmanv = new javax.swing.JComboBox<>();
        jtfmakh = new javax.swing.JTextField();
        jngayden = new com.toedter.calendar.JDateChooser();

        jPanel2.setBackground(new java.awt.Color(0, 90, 134));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 34)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CẬP NHẬT PHIẾU NHẬN PHÒNG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(1, 50, 67));

        jLabel4.setBackground(new java.awt.Color(247, 202, 24));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 34)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(247, 202, 24));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CẬP NHẬT PHIẾU NHẬN PHÒNG");

        jngayroi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jbsua.setBackground(new java.awt.Color(247, 202, 24));
        jbsua.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jbsua.setForeground(new java.awt.Color(1, 50, 67));
        jbsua.setText("Cập nhật");
        jbsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsuaActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(247, 202, 24));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(247, 202, 24));
        jLabel2.setText("Mã phiếu nhận");

        jbhuy.setBackground(new java.awt.Color(247, 202, 24));
        jbhuy.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jbhuy.setForeground(new java.awt.Color(1, 50, 67));
        jbhuy.setText("Hủy");
        jbhuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbhuyActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(247, 202, 24));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(247, 202, 24));
        jLabel3.setText("Mã khách hàng");

        jsonguoidikem.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel5.setBackground(new java.awt.Color(247, 202, 24));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(247, 202, 24));
        jLabel5.setText("Tên nhân viên");

        showdataforjloaiphong();
        jloaiphong.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jloaiphong.setEnabled(false);
        jloaiphong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jloaiphongItemStateChanged(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(247, 202, 24));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(247, 202, 24));
        jLabel6.setText("Số người đi kèm");

        jLabel9.setBackground(new java.awt.Color(247, 202, 24));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(247, 202, 24));
        jLabel9.setText("Tên loại phòng");

        jLabel7.setBackground(new java.awt.Color(247, 202, 24));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(247, 202, 24));
        jLabel7.setText("Ngày đến");

        jphong.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jphong.setEnabled(false);

        jLabel8.setBackground(new java.awt.Color(247, 202, 24));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(247, 202, 24));
        jLabel8.setText("Ngày rời");

        jLabel10.setBackground(new java.awt.Color(247, 202, 24));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(247, 202, 24));
        jLabel10.setText("Mã phòng");

        jtfmaphieu.setEditable(false);
        jtfmaphieu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtfmaphieu.setEnabled(false);

        NHANVIEN_BUS nhanvien = new NHANVIEN_BUS();
        List<NHANVIEN_TT> nv = new ArrayList<>();
        nv = nhanvien.getTTNhanVien();
        for(int i = 0; i< nv.size(); i++){
            jmanv.addItem(nv.get(i));
        }
        jmanv.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jtfmakh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtfmakh.setEnabled(false);

        jngayden.setEnabled(false);
        jngayden.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jbsua, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(115, 115, 115)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbhuy)
                    .addComponent(jphong, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jloaiphong, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jngayroi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jngayden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfmakh, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(jtfmaphieu, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(jsonguoidikem, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmanv, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel5, jLabel6, jLabel7, jLabel8});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jngayden, jngayroi, jtfmakh, jtfmaphieu});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbhuy, jbsua});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfmaphieu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jtfmakh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jmanv, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jsonguoidikem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jngayden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jngayroi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jloaiphong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jphong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbhuy)
                    .addComponent(jbsua, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel5, jLabel6, jLabel7, jLabel8});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jngayden, jngayroi, jtfmakh, jtfmaphieu});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbhuy, jbsua});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        public void showdataforjloaiphong(){
        PHIEUDATTRUOC_BUS pdt = new PHIEUDATTRUOC_BUS();
        List<LOAIPHONG> lp = new ArrayList<>();
        lp = pdt.getListLoaiPhong();
        for(int i = 0; i < lp.size(); i++){
            jloaiphong.addItem(lp.get(i));
        }
    }
    public void showdataforjphong(){
        PHIEUDATTRUOC_BUS pdt = new PHIEUDATTRUOC_BUS();
        List<Integer> maphong = new ArrayList<>();
        try{
            Date date = jngayden.getDate();
            SimpleDateFormat dateformat = new SimpleDateFormat("dd-MM-YYYY");
            String ngayden = dateformat.format(date);
            date = jngayroi.getDate();
            String ngayroi = dateformat.format(date);
            System.out.println(ngayden + " " + ngayroi);
            LOAIPHONG a = (LOAIPHONG)jloaiphong.getSelectedItem();
            maphong = pdt.getListPhongTrong(ngayden, ngayroi,a.getMALOAIPHONG());
            jphong.removeAllItems();
            for(int i = 0; i < maphong.size(); i++){
                this.jphong.addItem(String.valueOf(maphong.get(i)));
            }
            Random rd = new Random();
            int n = maphong.get(rd.nextInt(maphong.size()));
            System.out.println(n);
            jphong.setSelectedItem(String.valueOf(n));
        }catch(Exception e){
            System.out.println("Không có ngày");
        }
    }
        public void showdataforjsonguoidikem(){
        LOAIPHONG lp = (LOAIPHONG)jloaiphong.getSelectedItem();
        int n = lp.getSOLUONGNGUOI();
        System.out.println(n);
        jsonguoidikem.removeAllItems();
        for(int i = 1; i < n; i++){
            jsonguoidikem.addItem(String.valueOf(i));
        }
    }
    private void jloaiphongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jloaiphongItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() == java.awt.event.ItemEvent.SELECTED){
            LOAIPHONG phong = (LOAIPHONG)evt.getItem();
            showdataforjphong();
            showdataforjsonguoidikem();
        }
    }//GEN-LAST:event_jloaiphongItemStateChanged

    private void jbsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsuaActionPerformed
        // TODO add your handling code here:
        PHIEUNHANPHONG_BUS pnp = new PHIEUNHANPHONG_BUS();
        PHIEUNHANPHONG np = new PHIEUNHANPHONG();
        np.setMAPHIEUNHAN(Integer.parseInt(jtfmaphieu.getText()));
        np.setMAKH(Integer.parseInt(jtfmakh.getText()));
        Date date = jngayden.getDate();
        SimpleDateFormat dateformat = new SimpleDateFormat("dd-MM-YYYY");
        String ngayden = dateformat.format(date);
        np.setNGAYDEN(ngayden); 
        date = jngayroi.getDate();
        String ngayroi = dateformat.format(date);
        np.setNGAYROI(ngayroi);
        np.setMAPHONG(Integer.parseInt(jphong.getSelectedItem().toString()));
        NHANVIEN_TT nv = (NHANVIEN_TT)jmanv.getSelectedItem();
        np.setMANV(nv.getMANV());
        np.setSONGUOIDIKEM(Integer.parseInt(jsonguoidikem.getSelectedItem().toString()));
        try{
            boolean rs = pnp.updatePhieuNhanPhong(np);
            if(rs == true){
                JOptionPane.showMessageDialog(null, "Cập nhật phiếu nhận phòng thành công");
                showListPhieuNhanPhong();
                showListPhieuDatTruoc();
            }
            else{
                JOptionPane.showMessageDialog(null, "Cập nhật phiếu nhận phòng thất bại");
                showListPhieuNhanPhong();
                showListPhieuDatTruoc();                
            }       
        }catch(SQLException e){
            if(e.getErrorCode() == 20017)
                JOptionPane.showMessageDialog(null, "Không thể gia hạn cho phiếu nhận phòng. Đã có phiếu đặt trước!");
            else if(e.getErrorCode() == 20018)
                JOptionPane.showMessageDialog(null, "Không thể cập nhật mã phòng khác với cùng ngày rời");
        }
    }//GEN-LAST:event_jbsuaActionPerformed

    private void jbhuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbhuyActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jbhuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapNhatPhieuNhanPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapNhatPhieuNhanPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapNhatPhieuNhanPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapNhatPhieuNhanPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CapNhatPhieuNhanPhong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbhuy;
    private javax.swing.JButton jbsua;
    private javax.swing.JComboBox<LOAIPHONG> jloaiphong;
    private javax.swing.JComboBox<NHANVIEN_TT> jmanv;
    private com.toedter.calendar.JDateChooser jngayden;
    private com.toedter.calendar.JDateChooser jngayroi;
    private javax.swing.JComboBox<String> jphong;
    private javax.swing.JComboBox<String> jsonguoidikem;
    private javax.swing.JTextField jtfmakh;
    private javax.swing.JTextField jtfmaphieu;
    // End of variables declaration//GEN-END:variables
}
