/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.CSVC_BUS;
import static GUI.QUANLICSVC.showCSVC;
import DTO.CSVC;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class CapNhatCoSoVatChat extends javax.swing.JFrame {

    /**
     * Creates new form CapNhatCoSoVatChat
     */
    public CapNhatCoSoVatChat() {
        initComponents();
    }

    public CapNhatCoSoVatChat(int ma, String ten, int gia){
        initComponents();
        jtfma.setText(String.valueOf(ma));
        jtften.setText(ten);
        jtfgia.setText(String.valueOf(gia));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfma = new javax.swing.JTextField();
        jtften = new javax.swing.JTextField();
        jtfgia = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jbhuy = new javax.swing.JButton();
        jbsua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(1, 50, 67));

        jLabel1.setBackground(new java.awt.Color(1, 50, 67));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 202, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cập nhật cơ sở vật chất");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 100));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(247, 202, 24));
        jLabel2.setText("Mã cơ sở vật chất");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 118, 122, 32));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(247, 202, 24));
        jLabel3.setText("Tên cơ sở vật chất");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 168, 122, 32));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(247, 202, 24));
        jLabel4.setText("Giá cơ sở vật chất");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 218, 122, 32));

        jtfma.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jtfma.setEnabled(false);
        getContentPane().add(jtfma, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 118, 212, 32));

        jtften.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        getContentPane().add(jtften, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 168, 212, 32));

        jtfgia.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        getContentPane().add(jtfgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 218, 212, 32));

        jPanel1.setBackground(new java.awt.Color(1, 50, 67));
        jPanel1.setForeground(new java.awt.Color(247, 202, 24));

        jbhuy.setBackground(new java.awt.Color(247, 202, 24));
        jbhuy.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jbhuy.setForeground(new java.awt.Color(1, 50, 67));
        jbhuy.setText("Hủy");
        jbhuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbhuyActionPerformed(evt);
            }
        });

        jbsua.setBackground(new java.awt.Color(247, 202, 24));
        jbsua.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jbsua.setForeground(new java.awt.Color(1, 50, 67));
        jbsua.setText("Sửa");
        jbsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jbsua, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(jbhuy, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbhuy, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbsua, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 460, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbhuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbhuyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbhuyActionPerformed

    private void jbsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsuaActionPerformed
        // TODO add your handling code here:
        if(jtften.getText().equals("") || jtfgia.getText().equals(""))
            JOptionPane.showMessageDialog(rootPane,"Vui lòng nhập đầy đủ thông tin");
        else{
            CSVC_BUS csvc = new CSVC_BUS();
            CSVC cs = new CSVC();
            cs.setMACSVC(Integer.parseInt(jtfma.getText()));
            cs.setTENCSVC(jtften.getText());
            cs.setGIACSVC(Integer.parseInt(jtfgia.getText()));
            boolean rs = csvc.updateCSVC(cs);
            if(rs == true){
                JOptionPane.showMessageDialog(rootPane, "Cập nhật cơ sở vật chất thành công");
                showCSVC();
            }
            else
                JOptionPane.showMessageDialog(rootPane, "Cập nhật cơ sở vật chất thất bại");
        }
    }//GEN-LAST:event_jbsuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapNhatCoSoVatChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapNhatCoSoVatChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapNhatCoSoVatChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapNhatCoSoVatChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CapNhatCoSoVatChat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbhuy;
    private javax.swing.JButton jbsua;
    private javax.swing.JTextField jtfgia;
    private javax.swing.JTextField jtfma;
    private javax.swing.JTextField jtften;
    // End of variables declaration//GEN-END:variables
}
