/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.NHANVIEN_BUS;
import BUS.PHIEUDATTRUOC_BUS;
import Class.NHANVIEN_TT;
import DTO.PHIEUDATTRUOC;
import COMBOBOX.PHONGTRONG;
import static DAO.OracleConnection.Connection;
import static GUI.QuanLyThongTinDatTruoc.showListPhieuDatTruoc;
import static GUI.QuanLyThongTinNhanPhong.showListPhieuNhanPhong;
import DTO.LOAIPHONG;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.SQLException;

/**
 *
 * @author HP
 */
public class CapNhatPhieuDatTruoc extends javax.swing.JFrame {

    /**
     * Creates new form CapNhatPhieuDatTruoc
     */
    public CapNhatPhieuDatTruoc() {
        initComponents();
    }
    
    public CapNhatPhieuDatTruoc(PHIEUDATTRUOC pdt){
        initComponents();
        jtfmaphieu.setText(String.valueOf(pdt.getMAPHIEU()));
        jtfmakh.setText(String.valueOf(pdt.getMAKH()));
        NHANVIEN_BUS nhanvien = new NHANVIEN_BUS();
        String ten = nhanvien.getTenNhanVien(pdt.getMANV());
        NHANVIEN_TT nv = new NHANVIEN_TT(pdt.getMANV(),ten);
        PHIEUDATTRUOC_BUS dt = new PHIEUDATTRUOC_BUS();
        LOAIPHONG lp = dt.getTTLoaiPhong(pdt.getMAPHONG());
        jloaiphong.getModel().setSelectedItem(lp);
        jmanv.getModel().setSelectedItem(nv);
        jphong.getModel().setSelectedItem(String.valueOf(pdt.getMAPHONG()));
        try{
            java.util.Date date = new SimpleDateFormat("dd-MM-yyyy").parse(pdt.getNGAYDEN()); 
            jngayden.setDate(date);
            date = new SimpleDateFormat("dd-MM-yyyy").parse(pdt.getNGAYROI());
            jngayroi.setDate(date);
        }catch(Exception e){
            e.printStackTrace();
        }
        if(pdt.getTINHTRANG().equals("CHƯA NHẬN"))
           jtinhtrang.setSelected(false);
        else
           jtinhtrang.setSelected(true);
        int n = lp.getSOLUONGNGUOI();
//        for(int i = 1; i < n; i++){
//            jsonguoidikem.addItem(String.valueOf(i));
//        }
        jsonguoidikem.setSelectedItem(String.valueOf(pdt.getSONGUOIDIKEM()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfmaphieu = new javax.swing.JTextField();
        jngayden = new com.toedter.calendar.JDateChooser();
        jngayroi = new com.toedter.calendar.JDateChooser();
        jtfmakh = new javax.swing.JTextField();
        jtinhtrang = new javax.swing.JCheckBox();
        jmanv = new javax.swing.JComboBox<>();
        jloaiphong = new javax.swing.JComboBox<>();
        jphong = new javax.swing.JComboBox<>();
        jbsua = new javax.swing.JButton();
        jbhuy = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jsonguoidikem = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(1, 50, 67));
        jPanel2.setForeground(new java.awt.Color(247, 202, 24));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 34)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 202, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CẬP NHẬT PHIẾU ĐẶT PHÒNG");

        jPanel3.setBackground(new java.awt.Color(1, 50, 67));
        jPanel3.setForeground(new java.awt.Color(247, 202, 24));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(247, 202, 24));
        jLabel2.setText("Mã phiếu đặt");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(247, 202, 24));
        jLabel3.setText("Ngày đến");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(247, 202, 24));
        jLabel4.setText("Ngày rời");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(247, 202, 24));
        jLabel5.setText("Tên loại phòng");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(247, 202, 24));
        jLabel6.setText("Mã phòng");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(247, 202, 24));
        jLabel7.setText("Mã khách hàng");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(247, 202, 24));
        jLabel8.setText("Tên nhân viên");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(247, 202, 24));
        jLabel9.setText("Tình trạng");

        jtfmaphieu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtfmaphieu.setEnabled(false);

        jngayden.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jngayroi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jtfmakh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtfmakh.setEnabled(false);

        jtinhtrang.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtinhtrang.setText("Đã nhận phòng");

        NHANVIEN_BUS nhanvien = new NHANVIEN_BUS();
        List<NHANVIEN_TT> nv = new ArrayList<>();
        nv = nhanvien.getTTNhanVien();
        for(int i = 0; i< nv.size(); i++){
            jmanv.addItem(nv.get(i));
        }
        jmanv.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        showdataforjloaiphong();
        jloaiphong.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jloaiphong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jloaiphongItemStateChanged(evt);
            }
        });

        jphong.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jphong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jphongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jphongMouseEntered(evt);
            }
        });

        jbsua.setBackground(new java.awt.Color(247, 202, 24));
        jbsua.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jbsua.setForeground(new java.awt.Color(1, 50, 67));
        jbsua.setText("Cập nhật");
        jbsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsuaActionPerformed(evt);
            }
        });

        jbhuy.setBackground(new java.awt.Color(247, 202, 24));
        jbhuy.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jbhuy.setForeground(new java.awt.Color(1, 50, 67));
        jbhuy.setText("Hủy");
        jbhuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbhuyActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(247, 202, 24));
        jLabel10.setText("Số người đi kèm");

        jsonguoidikem.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jbsua, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbhuy, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtinhtrang, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jtfmakh, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jngayroi, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jngayden, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jtfmaphieu, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jmanv, 0, 200, Short.MAX_VALUE)
                    .addComponent(jloaiphong, 0, 200, Short.MAX_VALUE)
                    .addComponent(jphong, 0, 200, Short.MAX_VALUE)
                    .addComponent(jsonguoidikem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfmaphieu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jngayden, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jngayroi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jloaiphong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jphong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jtfmakh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jmanv, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jtinhtrang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jsonguoidikem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbsua, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbhuy, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void showdataforjloaiphong(){
        PHIEUDATTRUOC_BUS pdt = new PHIEUDATTRUOC_BUS();
        List<LOAIPHONG> lp = new ArrayList<>();
        lp = pdt.getListLoaiPhong();
        for(int i = 0; i < lp.size(); i++){
            jloaiphong.addItem(lp.get(i));
        }
    }
    public void showdataforjphong(){
        PHIEUDATTRUOC_BUS pdt = new PHIEUDATTRUOC_BUS();
        List<Integer> maphong = new ArrayList<>();
        try{
            Date date = jngayden.getDate();
            SimpleDateFormat dateformat = new SimpleDateFormat("dd-MM-YYYY");
            String ngayden = dateformat.format(date);
            date = jngayroi.getDate();
            String ngayroi = dateformat.format(date);
            System.out.println(ngayden + " " + ngayroi);
            LOAIPHONG a = (LOAIPHONG)jloaiphong.getSelectedItem();
            maphong = pdt.getListPhongTrong(ngayden, ngayroi,a.getMALOAIPHONG());
            jphong.removeAllItems();
            for(int i = 0; i < maphong.size(); i++){
                this.jphong.addItem(String.valueOf(maphong.get(i)));
            }
            Random rd = new Random();
            int n = maphong.get(rd.nextInt(maphong.size()));
            System.out.println(n);
            jphong.setSelectedItem(String.valueOf(n));
        }catch(Exception e){
            System.out.println("Không có ngày");
        }
    }
        public void showdataforjsonguoidikem(){
        LOAIPHONG lp = (LOAIPHONG)jloaiphong.getSelectedItem();
        int n = lp.getSOLUONGNGUOI();
        System.out.println(n);
        jsonguoidikem.removeAllItems();
        for(int i = 0; i < n; i++){
            jsonguoidikem.addItem(String.valueOf(i));
        }
    }
    private void jloaiphongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jloaiphongItemStateChanged
        // TODO add your handling code here:
            if(evt.getStateChange() == java.awt.event.ItemEvent.SELECTED){
            LOAIPHONG phong = (LOAIPHONG)evt.getItem();
            showdataforjphong();
            showdataforjsonguoidikem();
        }
    }//GEN-LAST:event_jloaiphongItemStateChanged

    private void jphongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jphongMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jphongMouseEntered

    private void jphongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jphongMouseClicked
        // TODO add your handling code here:
        showdataforjphong();
    }//GEN-LAST:event_jphongMouseClicked

    private void jbsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsuaActionPerformed
        // TODO add your handling code here:
        PHIEUDATTRUOC_BUS pdt = new PHIEUDATTRUOC_BUS();
        PHIEUDATTRUOC dt = new PHIEUDATTRUOC();
        dt.setMAKH(Integer.parseInt(jtfmakh.getText()));
        dt.setMAPHIEU(Integer.parseInt(jtfmaphieu.getText()));
        Date date = jngayden.getDate();
        SimpleDateFormat dateformat = new SimpleDateFormat("dd-MM-YYYY");
        String ngayden = dateformat.format(date);
        dt.setNGAYDEN(ngayden); 
        date = jngayroi.getDate();
        String ngayroi = dateformat.format(date);
        dt.setNGAYROI(ngayroi);
        dt.setMAPHONG(Integer.parseInt(jphong.getSelectedItem().toString()));
        NHANVIEN_TT nv = (NHANVIEN_TT)jmanv.getSelectedItem();
        dt.setMANV(nv.getMANV());
        if(jtinhtrang.isSelected() == false)
            dt.setTINHTRANG("CHƯA NHẬN");
        else
            dt.setTINHTRANG("ĐÃ NHẬN");
        dt.setSONGUOIDIKEM(Integer.parseInt(jsonguoidikem.getSelectedItem().toString()));
        boolean rs = pdt.updatePhieuDatTruoc(dt);
        if(rs == true){
            JOptionPane.showMessageDialog(null,"Cập nhật phiếu đặt trước thành công");
        }else{
            JOptionPane.showMessageDialog(null, "Cập nhật phiếu đặt trước thất bại");
           
        }

    }//GEN-LAST:event_jbsuaActionPerformed

    private void jbhuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbhuyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbhuyActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapNhatPhieuDatTruoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapNhatPhieuDatTruoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapNhatPhieuDatTruoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapNhatPhieuDatTruoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CapNhatPhieuDatTruoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbhuy;
    private javax.swing.JButton jbsua;
    private javax.swing.JComboBox<LOAIPHONG> jloaiphong;
    private javax.swing.JComboBox<NHANVIEN_TT> jmanv;
    private com.toedter.calendar.JDateChooser jngayden;
    private com.toedter.calendar.JDateChooser jngayroi;
    private javax.swing.JComboBox<String> jphong;
    private javax.swing.JComboBox<String> jsonguoidikem;
    private javax.swing.JTextField jtfmakh;
    private javax.swing.JTextField jtfmaphieu;
    private javax.swing.JCheckBox jtinhtrang;
    // End of variables declaration//GEN-END:variables
}
