/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import DTO.NHANVIEN;
import BUS.NHANVIEN_BUS;
import static GUI.QUANLINHANVIEN.jTable1;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class QUANLINHANVIEN extends javax.swing.JPanel {

    /**
     * Creates new form QUANLINHANVIEN
     */
    public QUANLINHANVIEN() {
        initComponents();
        showNhanVien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtffind = new javax.swing.JTextField();
        jbFind = new javax.swing.JButton();
        jBThem = new javax.swing.JButton();
        jBXoa = new javax.swing.JButton();
        jBSua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(740, 600));

        jPanel1.setBackground(new java.awt.Color(1, 50, 67));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 202, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ NHÂN VIÊN");

        jtffind.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtffind.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtffind.setText("CMND");

        jbFind.setBackground(new java.awt.Color(247, 202, 24));
        jbFind.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbFind.setForeground(new java.awt.Color(1, 50, 67));
        jbFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_search_20px.png"))); // NOI18N
        jbFind.setText("Tìm kiếm");
        jbFind.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbFind.setMaximumSize(new java.awt.Dimension(113, 30));
        jbFind.setMinimumSize(new java.awt.Dimension(120, 30));
        jbFind.setPreferredSize(new java.awt.Dimension(120, 30));
        jbFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFindActionPerformed(evt);
            }
        });

        jBThem.setBackground(new java.awt.Color(247, 202, 24));
        jBThem.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jBThem.setForeground(new java.awt.Color(1, 50, 67));
        jBThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_plus_math_20px.png"))); // NOI18N
        jBThem.setText("Thêm");
        jBThem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBThemActionPerformed(evt);
            }
        });

        jBXoa.setBackground(new java.awt.Color(247, 202, 24));
        jBXoa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jBXoa.setForeground(new java.awt.Color(1, 50, 67));
        jBXoa.setText("Xóa");
        jBXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBXoaActionPerformed(evt);
            }
        });

        jBSua.setBackground(new java.awt.Color(247, 202, 24));
        jBSua.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jBSua.setForeground(new java.awt.Color(1, 50, 67));
        jBSua.setText("Sửa");
        jBSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSuaActionPerformed(evt);
            }
        });

        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTable1.setBackground(new java.awt.Color(1, 50, 67));
        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(247, 202, 24));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên Nhân viên", "Ngày Sinh", "Giới tính", "CMND", "Địa chỉ", "Số điện thoại", "Ngày vào làm", "Người Quản lý"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 90, 134));
        jTable1.setPreferredSize(new java.awt.Dimension(740, 600));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jtffind, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSua, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbFind, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBThem)
                        .addComponent(jBXoa)
                        .addComponent(jBSua))
                    .addComponent(jtffind, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public static void showNhanVien(){
        List<NHANVIEN> nhanvien = new ArrayList<>();
        NHANVIEN_BUS nv = new NHANVIEN_BUS();
        Component rootPane = null;
        if(nv.getListNhanVien() != null){
            javax.swing.table.DefaultTableModel mode;
            mode = (javax.swing.table.DefaultTableModel)jTable1.getModel();
            mode.setNumRows(0);
            nhanvien = nv.getListNhanVien();
            for(int i = 0; i < nhanvien.size(); i++){
                mode.addRow(new Object[]{nhanvien.get(i).getTENNV(), nhanvien.get(i).getNAMSINH(),
                    nhanvien.get(i).getGIOITINH(), nhanvien.get(i).getCMND()
                    , nhanvien.get(i).getDIACHI(), nhanvien.get(i).getSDT(),
                    nhanvien.get(i).getNGAYVAOLAM(),nhanvien.get(i).getTENQL()
                });
            }
        }
        else
            JOptionPane.showMessageDialog(rootPane,"Không có dữ liệu để hiển thị");
    }  
    private void jbFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFindActionPerformed
        // TODO add your handling code here:
        NHANVIEN_BUS nv = new NHANVIEN_BUS();
        NHANVIEN nhanvien = new NHANVIEN();
        if(nv.findNhanVien(jtffind.getText())){
            nhanvien = nv.getNhanVienByCMND(jtffind.getText());
            ThongTinChiTietNhanVien ttnhanvien = new ThongTinChiTietNhanVien(nhanvien.getMANV(), nhanvien.getTENNV()
                , nhanvien.getNAMSINH(), nhanvien.getGIOITINH(), nhanvien.getCMND(), nhanvien.getDIACHI()
                , nhanvien.getSDT(), nhanvien.getEMAIL(), nhanvien.getNGAYVAOLAM(), nhanvien.getTENTAIKHOAN()
                , nhanvien.getMATKHAU(), nhanvien.getTENQL(), nhanvien.getTENLOAITK());
            ttnhanvien.setVisible(true);
        }
        else if(jTable1.getSelectedRow() != -1){
            int column = 3;
            int row = jTable1.getSelectedRow();
            String find = jTable1.getModel().getValueAt(row, column).toString();
            nhanvien = nv.getNhanVienByCMND(find);
            ThongTinChiTietNhanVien ttnhanvien = new ThongTinChiTietNhanVien(nhanvien.getMANV(), nhanvien.getTENNV()
                , nhanvien.getNAMSINH(), nhanvien.getGIOITINH(), nhanvien.getCMND(), nhanvien.getDIACHI()
                , nhanvien.getSDT(), nhanvien.getEMAIL(), nhanvien.getNGAYVAOLAM(), nhanvien.getTENTAIKHOAN()
                , nhanvien.getMATKHAU(), nhanvien.getTENQL(), nhanvien.getTENLOAITK());
            ttnhanvien.setVisible(true);
        }
        else
        JOptionPane.showMessageDialog(null,"Không tìm thấy nhân viên cần tìm");
    }//GEN-LAST:event_jbFindActionPerformed

    private void jBThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBThemActionPerformed
        // TODO add your handling code here:
        ThemNhanVien tnv = new ThemNhanVien();
        tnv.setVisible(true);

    }//GEN-LAST:event_jBThemActionPerformed

    private void jBXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBXoaActionPerformed
        // TODO add your handling code here:
        javax.swing.table.DefaultTableModel mode;
        mode = (javax.swing.table.DefaultTableModel)this.jTable1.getModel();
        NHANVIEN_BUS nhanvien = new NHANVIEN_BUS();
        Component rootPane = null;
        NHANVIEN nv = new NHANVIEN();
        if(nhanvien.findNhanVien(jtffind.getText()) == true){
            nv = nhanvien.getNhanVienByCMND(jtffind.getText());
            mode.setNumRows(0);
            mode.addRow(new Object[]{nv.getMANV(), nv.getTENNV(), nv.getNAMSINH(),
                nv.getGIOITINH(), nv.getCMND()
                , nv.getDIACHI(), nv.getSDT(),
                nv.getEMAIL(), nv.getNGAYVAOLAM(), nv.getTENTAIKHOAN(),
                nv.getMATKHAU(), nv.getNGUOIQUANLY(), nv.getTENLOAITK()
            });
            int buttonoption = JOptionPane.showConfirmDialog(rootPane,"Bạn có chắc chắn muốn xóa nhân viên");
            if(buttonoption == JOptionPane.YES_OPTION){
                boolean n = nhanvien.deleteNhanVien(jtffind.getText());
                mode.removeRow(0);
                if(n == true)
                JOptionPane.showMessageDialog(rootPane,"Xóa nhân viên thành công");
                else
                JOptionPane.showMessageDialog(rootPane,"Xóa nhân viên không thành công");
            }
        }
        else if(jTable1.getSelectedRow() != -1){
            int column = 3;
            int row = jTable1.getSelectedRow();
            String find = jTable1.getModel().getValueAt(row, column).toString();
            nv = nhanvien.getNhanVienByCMND(find);
            mode.setNumRows(0);
            mode.addRow(new Object[]{nv.getMANV(), nv.getTENNV(), nv.getNAMSINH(),
                nv.getGIOITINH(), nv.getCMND()
                , nv.getDIACHI(), nv.getSDT(),
                nv.getEMAIL(), nv.getNGAYVAOLAM(), nv.getTENTAIKHOAN(),
                nv.getMATKHAU(), nv.getNGUOIQUANLY(), nv.getTENLOAITK()
            });
            int buttonoption = JOptionPane.showConfirmDialog(rootPane,"Bạn có chắc chắn muốn xóa nhân viên");
            if(buttonoption == JOptionPane.YES_OPTION){
                boolean n = nhanvien.deleteNhanVien(find);
                mode.removeRow(0);
                if(n == true)
                JOptionPane.showMessageDialog(rootPane,"Xóa nhân viên thành công");
                else
                JOptionPane.showMessageDialog(rootPane,"Xóa nhân viên không thành công");
            }
        }
        else{
            int button = JOptionPane.showConfirmDialog(rootPane, "Không tìm thấy nhân viên. Vui lòng nhập lại");
            if(button == JOptionPane.NO_OPTION)
            System.exit(0);
        }

    }//GEN-LAST:event_jBXoaActionPerformed

    private void jBSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSuaActionPerformed
        // TODO add your handling code here:
        NHANVIEN_BUS nhanvien = new NHANVIEN_BUS();
        Component rootPane = null;
        NHANVIEN nv = new NHANVIEN();
        if(nhanvien.findNhanVien(jtffind.getText())){
            nv= nhanvien.getNhanVienByCMND(jtffind.getText());
            CapNhatNhanVien capnhat = new CapNhatNhanVien(nv.getMANV(), nv.getTENNV(), nv.getNAMSINH(),
                nv.getGIOITINH(), nv.getCMND()
                , nv.getDIACHI(), nv.getSDT(),
                nv.getEMAIL(), nv.getNGAYVAOLAM(), nv.getTENTAIKHOAN(),
                nv.getMATKHAU(), nv.getNGUOIQUANLY(), nv.getMALOAITK());
            capnhat.setVisible(true);
        }
        else if(jTable1.getSelectedRow() != -1){
            int column = 3;
            int row = jTable1.getSelectedRow();
            String find = jTable1.getModel().getValueAt(row, column).toString();
            nv = nhanvien.getNhanVienByCMND(find);
            CapNhatNhanVien capnhat = new CapNhatNhanVien(nv.getMANV(), nv.getTENNV(), nv.getNAMSINH(),
                nv.getGIOITINH(), nv.getCMND()
                , nv.getDIACHI(), nv.getSDT(),
                nv.getEMAIL(), nv.getNGAYVAOLAM(), nv.getTENTAIKHOAN(),
                nv.getMATKHAU(), nv.getNGUOIQUANLY(), nv.getMALOAITK());
            capnhat.setVisible(true);
        }
        else{
            int optionbutton = JOptionPane.showConfirmDialog(rootPane, "Không tìm thấy nhân viên. Vui lòng nhập lại");
            if(optionbutton == JOptionPane.NO_OPTION)
            System.exit(0);
        }
    }//GEN-LAST:event_jBSuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSua;
    private javax.swing.JButton jBThem;
    private javax.swing.JButton jBXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JButton jbFind;
    private javax.swing.JTextField jtffind;
    // End of variables declaration//GEN-END:variables
}
