/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.OracleConnection;
import java.io.*;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;





/**
 *
 * @author ADMIN
 */
public class QuanLyThongKe extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyThongKe
     */
    public QuanLyThongKe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KhachHang = new javax.swing.JButton();
        LoaiPhong = new javax.swing.JButton();
        MonAn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(1, 50, 67));

        KhachHang.setBackground(new java.awt.Color(247, 202, 24));
        KhachHang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        KhachHang.setForeground(new java.awt.Color(1, 50, 67));
        KhachHang.setText("THỐNG KÊ DOANH THU ");
        KhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KhachHangActionPerformed(evt);
            }
        });

        LoaiPhong.setBackground(new java.awt.Color(247, 202, 24));
        LoaiPhong.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LoaiPhong.setForeground(new java.awt.Color(1, 50, 67));
        LoaiPhong.setText("THỐNG KÊ SỐ LUONG ĐẶT PHÒNG THEO LOẠI PHÒNG");
        LoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoaiPhongActionPerformed(evt);
            }
        });

        MonAn.setBackground(new java.awt.Color(247, 202, 24));
        MonAn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        MonAn.setForeground(new java.awt.Color(1, 50, 67));
        MonAn.setText("TOP 3 MÓN ĂN ĐƯỢC ĐẶT NHIỀU NHẤT TRONG THÁNG");
        MonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonAnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 42)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 202, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THỐNG KÊ DOANH THU");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoaiPhong)
                    .addComponent(KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(LoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(MonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void KhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KhachHangActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = OracleConnection.Connection();
            //InputStream jrxml = this.getClass().getClassLoader().getResourceAsStream("KHACHHANG.jrxml");
            //InputStream pdf = this.getClass().getClassLoader().getResourceAsStream("KHACHHANG.pdf");
            
            String jrxml = "src\\ireport\\DOANHTHU_PHONG.jrxml";
            JasperDesign jd = JRXmlLoader.load(jrxml);
            JasperReport jr = JasperCompileManager.compileReport(jrxml);
            JasperPrint jp = JasperFillManager.fillReport(jr, new HashMap(), conn);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(QuanLyThongKe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyThongKe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_KhachHangActionPerformed

    private void MonAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonAnActionPerformed
        // TODO add your handling code here:
        ThangNamThongKe tk = new ThangNamThongKe();
        tk.setVisible(true);
    }//GEN-LAST:event_MonAnActionPerformed

    private void LoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoaiPhongActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = OracleConnection.Connection();
            //InputStream jrxml = this.getClass().getClassLoader().getResourceAsStream("THONGKELOAIPHONG.jrxml");
            //InputStream pdf = this.getClass().getClassLoader().getResourceAsStream("THONGKELOAIPHONG.pdf");
            String jrxml = "src\\ireport\\THONGKELOAIPHONG.jrxml";
            JasperDesign jd = JRXmlLoader.load(jrxml);
            JasperReport jr = JasperCompileManager.compileReport(jrxml);
            JasperPrint jp = JasperFillManager.fillReport(jr, new HashMap(), conn);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(QuanLyThongKe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyThongKe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LoaiPhongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KhachHang;
    private javax.swing.JButton LoaiPhong;
    private javax.swing.JButton MonAn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
