/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.KHACHHANG_BUS;
import DTO.KHACHHANG;
import static GUI.QUANLIKHACHHANG.jTable1;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class QUANLIKHACHHANG extends javax.swing.JPanel {

    /**
     * Creates new form QUANLIKHACHHANG
     */
    public QUANLIKHACHHANG() {
        initComponents();
        showListKhachHang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtffind = new javax.swing.JTextField();
        jbFind = new javax.swing.JButton();
        jBXoa = new javax.swing.JButton();
        jBSua = new javax.swing.JButton();
        THEM = new javax.swing.JButton();
        PNP = new javax.swing.JButton();
        PDT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(1, 50, 67));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 202, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ THÔNG TIN KHÁCH HÀNG");

        jtffind.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtffind.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtffind.setText("CMND");

        jbFind.setBackground(new java.awt.Color(247, 202, 24));
        jbFind.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbFind.setForeground(new java.awt.Color(1, 50, 67));
        jbFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_search_20px.png"))); // NOI18N
        jbFind.setText("Tìm kiếm");
        jbFind.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbFind.setMaximumSize(new java.awt.Dimension(113, 30));
        jbFind.setMinimumSize(new java.awt.Dimension(120, 30));
        jbFind.setPreferredSize(new java.awt.Dimension(120, 30));
        jbFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFindActionPerformed(evt);
            }
        });

        jBXoa.setBackground(new java.awt.Color(247, 202, 24));
        jBXoa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jBXoa.setForeground(new java.awt.Color(1, 50, 67));
        jBXoa.setText("Xóa");
        jBXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBXoaActionPerformed(evt);
            }
        });

        jBSua.setBackground(new java.awt.Color(247, 202, 24));
        jBSua.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jBSua.setForeground(new java.awt.Color(1, 50, 67));
        jBSua.setText("Sửa");
        jBSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSuaActionPerformed(evt);
            }
        });

        THEM.setBackground(new java.awt.Color(247, 202, 24));
        THEM.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        THEM.setForeground(new java.awt.Color(1, 50, 67));
        THEM.setText("Thêm");
        THEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THEMActionPerformed(evt);
            }
        });

        PNP.setBackground(new java.awt.Color(247, 202, 24));
        PNP.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        PNP.setForeground(new java.awt.Color(1, 50, 67));
        PNP.setText("Phiếu nhận phòng");
        PNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PNPActionPerformed(evt);
            }
        });

        PDT.setBackground(new java.awt.Color(247, 202, 24));
        PDT.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        PDT.setForeground(new java.awt.Color(1, 50, 67));
        PDT.setText("Phiếu đặt trước");
        PDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jtffind, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jBXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jBSua, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(THEM, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PDT, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PNP, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtffind, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbFind, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBSua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(THEM, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PNP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 130));

        jScrollPane1.setBackground(new java.awt.Color(247, 202, 24));
        jScrollPane1.setForeground(new java.awt.Color(1, 50, 67));
        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTable1.setBackground(new java.awt.Color(1, 50, 67));
        jTable1.setForeground(new java.awt.Color(247, 202, 24));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Khách Hàng", "Tên Khách Hàng", "Ngày Sinh", "CMND", "Giới tính", "Địa chỉ", "Số điện thoại", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 90, 134));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 740, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    public static void showListKhachHang(){
        List<KHACHHANG> kh = new ArrayList<>();
        KHACHHANG_BUS khachhang = new KHACHHANG_BUS();
        Component rootPane = null;
        if(khachhang.getListKhachHang() != null){
            javax.swing.table.DefaultTableModel mode;
            mode = (javax.swing.table.DefaultTableModel)jTable1.getModel();
            mode.setNumRows(0);
            kh = khachhang.getListKhachHang();
            for(int i = 0; i < kh.size(); i++){
               mode.addRow(new Object[]{kh.get(i).getMAKH(),kh.get(i).getHOTEN(),kh.get(i).getNAMSINH(),kh.get(i).getCMND(),
                                kh.get(i).getGIOITINH(),kh.get(i).getDIACHI(),kh.get(i).getSDT(),kh.get(i).getEMAIL()});
            }
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Không có dữ liệu để hiển thị");
    }
    private void jbFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFindActionPerformed
        // TODO add your handling code here:
        KHACHHANG_BUS khachhang = new KHACHHANG_BUS();
        javax.swing.table.DefaultTableModel mode;
        mode = (javax.swing.table.DefaultTableModel)this.jTable1.getModel();
        Component rootPane = null;
        KHACHHANG kh = new KHACHHANG();
        if(khachhang.findKhachHang(jtffind.getText())){
            kh = khachhang.getKhachHangByCMND(jtffind.getText());
            mode.setNumRows(0);
            mode.addRow(new Object[]{kh.getMAKH(),kh.getHOTEN(),kh.getNAMSINH(),kh.getCMND(),
                kh.getGIOITINH(),kh.getDIACHI(),kh.getSDT(),kh.getEMAIL()});
        }
        else if(jTable1.getSelectedRow() != 1){
            int column = 3;
            int row = jTable1.getSelectedRow();
            String find = jTable1.getValueAt(row, column).toString();
            kh = khachhang.getKhachHangByCMND(find);
            mode.setNumRows(0);
            mode.addRow(new Object[]{kh.getMAKH(),kh.getHOTEN(),kh.getNAMSINH(),kh.getCMND(),
                kh.getGIOITINH(),kh.getDIACHI(),kh.getSDT(),kh.getEMAIL()});
        }
        else{
            int button = JOptionPane.showConfirmDialog(rootPane,"Không tìm thấy khách hàng. Vui lòng nhập lại" );
            if(button == JOptionPane.NO_OPTION)
            System.exit(0);
        }
    }//GEN-LAST:event_jbFindActionPerformed

    private void jBXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBXoaActionPerformed
        // TODO add your handling code here:
        javax.swing.table.DefaultTableModel mode;
        mode = (javax.swing.table.DefaultTableModel)this.jTable1.getModel();
        KHACHHANG_BUS khachhang = new KHACHHANG_BUS();
        Component rootPane = null;
        KHACHHANG kh = new KHACHHANG();
        if(khachhang.findKhachHang(jtffind.getText())){
            kh = khachhang.getKhachHangByCMND(jtffind.getText());
            mode.setNumRows(0);
            mode.addRow(new Object[]{kh.getMAKH(),kh.getHOTEN(), kh.getNAMSINH(), kh.getCMND(), kh.getDIACHI()
                ,kh.getSDT(), kh.getEMAIL(),kh.getGIOITINH()});
        int buttonoption = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắc muốn xóa?");
        if(buttonoption == JOptionPane.YES_OPTION){
            boolean rs = khachhang.deleteKhachHang(jtffind.getText());
            mode.removeRow(0);
            if(rs == true)
            JOptionPane.showMessageDialog(rootPane,"Xóa khách hàng thành công");
            else
            JOptionPane.showMessageDialog(rootPane,"Xóa khách hàng thất bại");
        }
        }
        else if(jTable1.getSelectedRow() != -1){
            int column = 3;
            int row = jTable1.getSelectedRow();
            String find = jTable1.getValueAt(row, column).toString();
            kh = khachhang.getKhachHangByCMND(find);
            mode.setNumRows(0);
            mode.addRow(new Object[]{kh.getMAKH(),kh.getHOTEN(), kh.getNAMSINH(), kh.getCMND(), kh.getDIACHI()
                ,kh.getSDT(), kh.getEMAIL(),kh.getGIOITINH()});
        int buttonoption = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắc muốn xóa?");
        if(buttonoption == JOptionPane.YES_OPTION){
            boolean rs = khachhang.deleteKhachHang(find);
            mode.removeRow(0);
            if(rs == true){
                JOptionPane.showMessageDialog(rootPane,"Xóa khách hàng thành công");
                showListKhachHang();
            }
            else{
                JOptionPane.showMessageDialog(rootPane,"Xóa khách hàng thất bại");
                showListKhachHang();
            }
        }
        }
        else{
            int button = JOptionPane.showConfirmDialog(rootPane, "Không tìm thấy khách hàng. Vui lòng nhập lại");
            if(button == JOptionPane.NO_OPTION)
            System.exit(0);
        }
    }//GEN-LAST:event_jBXoaActionPerformed

    private void jBSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSuaActionPerformed
        // TODO add your handling code here:
        KHACHHANG_BUS khachhang = new KHACHHANG_BUS();
        KHACHHANG kh = new KHACHHANG();
        if(khachhang.findKhachHang(jtffind.getText())){
            kh = khachhang.getKhachHangByCMND(jtffind.getText());
            CapNhatKhachHang capnhat = new CapNhatKhachHang(kh.getMAKH(),kh.getHOTEN()
                ,kh.getNAMSINH(),kh.getCMND(),kh.getDIACHI(),kh.getSDT()
                ,kh.getEMAIL(),kh.getGIOITINH());
            capnhat.setVisible(true);
        }
        else if(jTable1.getSelectedRow() != -1){
            int column = 3;
            int row = jTable1.getSelectedRow();
            String find = jTable1.getValueAt(row, column).toString();
            kh = khachhang.getKhachHangByCMND(find);
            CapNhatKhachHang capnhat = new CapNhatKhachHang(kh.getMAKH(),kh.getHOTEN()
                ,kh.getNAMSINH(),kh.getCMND(),kh.getDIACHI(),kh.getSDT()
                ,kh.getEMAIL(),kh.getGIOITINH());
            capnhat.setVisible(true);
        }
        else{
            Component rootPane = null;
            int optionbutton = JOptionPane.showConfirmDialog(rootPane, "Không tìm thấy khách hàng. Vui lòng nhập lại");
            if(optionbutton == JOptionPane.NO_OPTION)
            System.exit(0);
        }
    }//GEN-LAST:event_jBSuaActionPerformed

    private void PNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PNPActionPerformed
        // TODO add your handling code here:
        QUANLIPHIEUNHANPHONG pnp = new QUANLIPHIEUNHANPHONG();
        pnp.setVisible(true);
    }//GEN-LAST:event_PNPActionPerformed

    private void PDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDTActionPerformed
        // TODO add your handling code here:
        QUANLIPHIEUDATTRUOC pdt = new QUANLIPHIEUDATTRUOC ();
        pdt.setVisible(true);
    }//GEN-LAST:event_PDTActionPerformed

    private void THEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THEMActionPerformed
        // TODO add your handling code here:
        KHACHHANG kh = new KHACHHANG();
        KHACHHANG_BUS khb = new KHACHHANG_BUS ();
        kh = khb.getKhachHangByCMND(jtffind.getText());
        System.out.println(kh);
        if (kh.getCMND() ==null)
        {
            ThemKhachHang tkh = new ThemKhachHang();
            tkh.jtfcmnd.setText(jtffind.getText());
            tkh.setVisible(true);
        }
        else
        {
            ThemPhieuNhanPhong tpn = new ThemPhieuNhanPhong ();
            tpn.jtfmakh.setText(Integer.toString(kh.getMAKH()));
            tpn.setVisible(true);
        }

    }//GEN-LAST:event_THEMActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PDT;
    private javax.swing.JButton PNP;
    private javax.swing.JButton THEM;
    private javax.swing.JButton jBSua;
    private javax.swing.JButton jBXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JButton jbFind;
    private javax.swing.JTextField jtffind;
    // End of variables declaration//GEN-END:variables
}
