/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.KHACHHANG_BUS;
import BUS.PHIEUDATTRUOC_BUS;
import COMBOBOX.KHACHHANG_TT;
import DTO.KHACHHANG;
import DTO.PHIEUDATTRUOC;
import java.awt.Frame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import static java.lang.Thread.sleep;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class QuanLyThongTinDatTruoc extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyThongTinDatTruoc
     */
    
    public static void showListPhieuDatTruoc(){
        PHIEUDATTRUOC_BUS phieudat = new PHIEUDATTRUOC_BUS();
        List<PHIEUDATTRUOC> pdt = new ArrayList<>();
        pdt = phieudat.getListPhieuDatTruoc();
        if(pdt != null){
            DefaultTableModel mode = new DefaultTableModel();
            mode = (DefaultTableModel)jTable1.getModel();
            mode.setNumRows(0);
            for(int i = 0; i < pdt.size(); i++){
                mode.addRow(new Object[]{pdt.get(i).getMAPHIEU(), pdt.get(i).getMAPHONG(),
                    pdt.get(i).getTENKH(), pdt.get(i).getTENNV(), pdt.get(i).getNGAYDEN()
                    ,pdt.get(i).getNGAYROI(), pdt.get(i).getTINHTRANG(),pdt.get(i).getSONGUOIDIKEM()});
            }
        }
        else
            JOptionPane.showMessageDialog(null,"Không có dữ liệu để hiển thị");
    }
            
    public QuanLyThongTinDatTruoc() {
        initComponents();
        showListPhieuDatTruoc();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtffind = new javax.swing.JTextField();
        jbFind = new javax.swing.JButton();
        jBThem = new javax.swing.JButton();
        jBXoa = new javax.swing.JButton();
        jBSua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(1, 50, 67));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 202, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ THÔNG TIN ĐẶT TRƯỚC");

        jtffind.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtffind.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtffind.setText("CMND");

        jbFind.setBackground(new java.awt.Color(247, 202, 24));
        jbFind.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbFind.setForeground(new java.awt.Color(1, 50, 67));
        jbFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_search_20px.png"))); // NOI18N
        jbFind.setText("Tìm kiếm");
        jbFind.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbFind.setMaximumSize(new java.awt.Dimension(113, 30));
        jbFind.setMinimumSize(new java.awt.Dimension(120, 30));
        jbFind.setPreferredSize(new java.awt.Dimension(120, 30));
        jbFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFindActionPerformed(evt);
            }
        });

        jBThem.setBackground(new java.awt.Color(247, 202, 24));
        jBThem.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jBThem.setForeground(new java.awt.Color(1, 50, 67));
        jBThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_plus_math_20px.png"))); // NOI18N
        jBThem.setText("Thêm");
        jBThem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBThemActionPerformed(evt);
            }
        });

        jBXoa.setBackground(new java.awt.Color(247, 202, 24));
        jBXoa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jBXoa.setForeground(new java.awt.Color(1, 50, 67));
        jBXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_delete_20px_1.png"))); // NOI18N
        jBXoa.setText("Xóa");
        jBXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBXoaActionPerformed(evt);
            }
        });

        jBSua.setBackground(new java.awt.Color(247, 202, 24));
        jBSua.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jBSua.setForeground(new java.awt.Color(1, 50, 67));
        jBSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_update_20px_1.png"))); // NOI18N
        jBSua.setText("Sửa");
        jBSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jtffind, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtffind, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbFind, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBThem)
                        .addComponent(jBXoa)
                        .addComponent(jBSua)))
                .addGap(0, 42, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        jTable1.setBackground(new java.awt.Color(1, 50, 67));
        jTable1.setForeground(new java.awt.Color(247, 202, 24));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu đặt trước", "Mã phòng", "Tên khách hàng", "Tên nhân viên", "Ngày đến", "Ngày rời", "Trạng thái", "Số người đi kèm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 740, 340));
    }// </editor-fold>//GEN-END:initComponents

    private void jbFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFindActionPerformed
        // TODO add your handling code here:
        PHIEUDATTRUOC_BUS phieudat = new PHIEUDATTRUOC_BUS();
        List<PHIEUDATTRUOC> pdt = new ArrayList<>();
        if(phieudat.findPhieuDatTruoc(jtffind.getText())){
            pdt = phieudat.getPhieuDatTruoc(jtffind.getText());
            DefaultTableModel mode = new DefaultTableModel();
            mode = (DefaultTableModel)jTable1.getModel();
            mode.setNumRows(0);
            for(int i = 0; i < pdt.size(); i++){
                mode.addRow(new Object[]{pdt.get(i).getMAPHIEU(), pdt.get(i).getMAPHONG(),
                    pdt.get(i).getTENKH(), pdt.get(i).getTENNV(), pdt.get(i).getNGAYDEN()
                    ,pdt.get(i).getNGAYROI(),pdt.get(i).getTINHTRANG(), pdt.get(i).getSONGUOIDIKEM()});
            }
        }else if(jTable1.getSelectedRow() != -1){
            int row = jTable1.getSelectedRow();
            PHIEUDATTRUOC pdt1 = new PHIEUDATTRUOC();
            pdt1.setMAPHIEU(Integer.parseInt(jTable1.getValueAt(row, 0).toString()));
            pdt1.setTENKH(jTable1.getValueAt(row, 2).toString());
            pdt1.setMAPHONG(Integer.parseInt(jTable1.getValueAt(row,1).toString()));
            pdt1.setTENNV(jTable1.getValueAt(row, 3).toString());
            pdt1.setNGAYDEN(jTable1.getValueAt(row, 4).toString());
            pdt1.setNGAYROI(jTable1.getValueAt(row, 5).toString());
            pdt1.setTINHTRANG(jTable1.getValueAt(row, 6).toString());
            pdt1.setSONGUOIDIKEM(Integer.parseInt(jTable1.getValueAt(row, 7).toString()));
            DefaultTableModel mode = new DefaultTableModel();
            mode = (DefaultTableModel)jTable1.getModel();
            mode.setNumRows(0);
            mode.addRow(new Object[]{pdt1.getMAPHIEU(), pdt1.getMAPHONG(),
                    pdt1.getTENKH(), pdt1.getTENNV(), pdt1.getNGAYDEN()
                    ,pdt1.getNGAYROI(), null});    
        }
        else
            JOptionPane.showMessageDialog(null,"Không tìm thấy phiếu đặt trước");
    }//GEN-LAST:event_jbFindActionPerformed

    private void jBThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBThemActionPerformed
        // TODO add your handling code here:
        PHIEUDATTRUOC_BUS pdt = new PHIEUDATTRUOC_BUS();
        KHACHHANG_BUS kh = new KHACHHANG_BUS();
        if(kh.findKhachHang(jtffind.getText())){
            KHACHHANG khachhang = new KHACHHANG();
            khachhang = kh.getKhachHangByCMND(jtffind.getText());
            ThemPhieuDatTruoc dt = new ThemPhieuDatTruoc(khachhang);
            dt.setVisible(true);
        }else{
            String find = jtffind.getText();
            ThemKhachHang tkh = new ThemKhachHang(find);
            tkh.setVisible(true);
            tkh.addWindowListener(new WindowAdapter(){
                public void windowClosed(WindowEvent e){
                    ThemPhieuDatTruoc dt = new ThemPhieuDatTruoc(kh.getKhachHangByCMND(jtffind.getText()));
                    dt.setVisible(true);
                }
        });
        }
    }//GEN-LAST:event_jBThemActionPerformed

    private void jBXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBXoaActionPerformed
        // TODO add your handling code here:
        PHIEUDATTRUOC_BUS pdt = new PHIEUDATTRUOC_BUS();
        int button = JOptionPane.showConfirmDialog(null,"Bạn có chắc chắn xóa phiếu đặt trước?");
        if(button == JOptionPane.YES_OPTION){
            if(jTable1.getRowCount() > 1){
                if(jTable1.getSelectedRow() != -1){
                    int find = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                    boolean rs = pdt.deletePhieuDatTruoc(find);
                    if(rs == true){
                        JOptionPane.showMessageDialog(null,"Xóa phiếu đặt trước thành công");
                        showListPhieuDatTruoc();
                    }else{
                        JOptionPane.showMessageDialog(null,"Xóa phiếu đặt trước thất bại");
                        showListPhieuDatTruoc();
                    }
                }
                else
                    JOptionPane.showMessageDialog(null, "Vui lòng chọn phiếu đặt trước cần xóa");
            }else{
                boolean rs = pdt.deletePhieuDatTruoc(Integer.parseInt(jTable1.getValueAt(0, 0).toString()));
                if(rs == true){
                    JOptionPane.showMessageDialog(null,"Xóa phiếu đặt trước thành công");
                    showListPhieuDatTruoc();
                }else{
                    JOptionPane.showMessageDialog(null,"Xóa phiếu đặt trước thất bại");
                    showListPhieuDatTruoc();
                }
            }  
        }
    }//GEN-LAST:event_jBXoaActionPerformed

    private void jBSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSuaActionPerformed
        // TODO add your handling code here:
        PHIEUDATTRUOC_BUS pdt = new PHIEUDATTRUOC_BUS();
        if(jTable1.getSelectedRow() > 1){
            if(jTable1.getSelectedRow() != -1){
                    int find = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(),0).toString());
                    PHIEUDATTRUOC dt = pdt.get1PhieuDatTruoc(find);
                    CapNhatPhieuDatTruoc cnpdt = new CapNhatPhieuDatTruoc(dt);
                    cnpdt.setVisible(true);
            }else 
                JOptionPane.showMessageDialog(null,"Vui lòng chọn phiếu đặt trước để cập nhật");         
        }else{
            int find = Integer.parseInt(jTable1.getValueAt(0,0).toString());
            PHIEUDATTRUOC dt = pdt.get1PhieuDatTruoc(find);
            CapNhatPhieuDatTruoc cnpdt = new CapNhatPhieuDatTruoc(dt);
            cnpdt.setVisible(true);
        }     
    }//GEN-LAST:event_jBSuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSua;
    private javax.swing.JButton jBThem;
    private javax.swing.JButton jBXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    private javax.swing.JButton jbFind;
    private javax.swing.JTextField jtffind;
    // End of variables declaration//GEN-END:variables
}
