/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Component;
import javax.swing.JOptionPane;
import BUS.HOADONTHANHTOAN_BUS;
import DAO.DAO_HOADONTHANHTOAN;
import DTO.HOADONTHANHTOAN_DTO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ADMIN
 */
public class QUANLIHOADONTHANHTOAN extends javax.swing.JFrame {

    /**
     * Creates new form HOADONTHANHTOAN
     */
    public QUANLIHOADONTHANHTOAN() {
        initComponents();
        ShowListHD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHoaDon = new javax.swing.JPanel();
        jTitle = new javax.swing.JLabel();
        jMaPhong = new javax.swing.JTextField();
        jSearch = new javax.swing.JButton();
        jDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtHD = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jHoaDon.setBackground(new java.awt.Color(1, 50, 67));

        jTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTitle.setForeground(new java.awt.Color(247, 202, 24));
        jTitle.setText("HÓA ĐƠN THANH TOÁN");

        jMaPhong.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jSearch.setBackground(new java.awt.Color(247, 202, 24));
        jSearch.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jSearch.setForeground(new java.awt.Color(1, 50, 67));
        jSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paradise_hotel/images/icons8_search_20px.png"))); // NOI18N
        jSearch.setText("Tìm Kiếm");
        jSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchActionPerformed(evt);
            }
        });

        jDelete.setBackground(new java.awt.Color(247, 202, 24));
        jDelete.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jDelete.setForeground(new java.awt.Color(1, 50, 67));
        jDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paradise_hotel/images/icons8_delete_20px.png"))); // NOI18N
        jDelete.setText("Xóa");
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });

        jtHD.setBackground(new java.awt.Color(1, 50, 67));
        jtHD.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jtHD.setForeground(new java.awt.Color(247, 202, 24));
        jtHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Mã nhân viên", "Mã phiếu nhận", "Mã phòng", "Tổng tiền", "Tình trạng", "Ngày đến", "Ngày rời"
            }
        ));
        jtHD.setGridColor(new java.awt.Color(247, 202, 24));
        jtHD.setRowHeight(40);
        jtHD.setRowMargin(5);
        jtHD.setShowGrid(true);
        jtHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtHDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtHD);

        javax.swing.GroupLayout jHoaDonLayout = new javax.swing.GroupLayout(jHoaDon);
        jHoaDon.setLayout(jHoaDonLayout);
        jHoaDonLayout.setHorizontalGroup(
            jHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitle)
                .addGap(55, 55, 55)
                .addComponent(jMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jSearch)
                .addGap(62, 62, 62)
                .addComponent(jDelete)
                .addContainerGap(138, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jHoaDonLayout.setVerticalGroup(
            jHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void ShowListHD()
    {
        List<HOADONTHANHTOAN_DTO> hds = new ArrayList<HOADONTHANHTOAN_DTO>();
        HOADONTHANHTOAN_BUS hd = new HOADONTHANHTOAN_BUS();
        Component frame = null;
        if(hd.getListHD() != null)
        {
            DefaultTableModel model = new DefaultTableModel ();
            model = (DefaultTableModel) jtHD.getModel();
            model.setNumRows(0);
            hds = hd.getListHD();
            for(int i=0; i < hds.size(); i++)
            {
                model.addRow(new Object[]{hds.get(i).getMAHD(),hds.get(i).getMANV(),hds.get(i).getMAPHIEUNHAN(),hds.get(i).getMaphong(),hds.get(i).getTONGTIEN(),hds.get(i).getTRANGTHAI(),hds.get(i).getNGAYDEN(),hds.get(i).getNGAYROI()});
            }
        }
        else
            JOptionPane.showMessageDialog(frame, "Không có dữ liệu để hiển thị");
    }
    private void jSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchActionPerformed
        // TODO add your handling code here:
        Component frame = null;
        if(jMaPhong.getText().equals("") == true)
            JOptionPane.showMessageDialog(frame,"Vui lòng nhập mã phòng");
        else
        {
            int Ma = Integer.parseInt(jMaPhong.getText());
            HOADONTHANHTOAN_BUS hdb = new HOADONTHANHTOAN_BUS();
            HOADONTHANHTOAN_DTO hd = new HOADONTHANHTOAN_DTO ();
            
            hd = hdb.getHDbyMAPHONG(Ma);
            if(hd != null)
            {                
                DefaultTableModel model = new DefaultTableModel ();
                model = (DefaultTableModel) jtHD.getModel();
                model.setRowCount(0);
                model.addRow(new Object[]{hd.getMAHD(),hd.getMANV(),hd.getMAPHIEUNHAN(),hd.getMaphong(),hd.getTONGTIEN(),hd.getTRANGTHAI(),hd.getNGAYDEN(),hd.getNGAYROI()});
            }
            else
            {
                JOptionPane.showMessageDialog(frame,"Không tìm thấy hóa đơn. Vui lòng nhập lại mã phòng");
            }
        }
       
        
        
    }//GEN-LAST:event_jSearchActionPerformed

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
        // TODO add your handling code here:
        HOADONTHANHTOAN_DTO hd = new HOADONTHANHTOAN_DTO();
        HOADONTHANHTOAN_BUS hdb = new HOADONTHANHTOAN_BUS();
        if (jMaPhong.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Vui lòng nhập phòng");
        }
        else 
       {
            int row =0;
            int map = Integer.parseInt(jMaPhong.getText());
            int buttonoption = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắc muốn xóa?");
            if(buttonoption == JOptionPane.YES_OPTION){
                hd = hdb.getHDbyMAPHONG(map);
                if (hdb.DELETE_HOADONTHANHTOAN(hd)==true)
                {
                    DefaultTableModel model = (DefaultTableModel)jtHD.getModel();
                    model.removeRow(row);
                    JOptionPane.showMessageDialog(null,"Xóa hóa đơn thành công");
                }
                else 
                    JOptionPane.showMessageDialog(null,"Xóa hóa đơn thất bại");
               
            }
               else
            {
                int button = JOptionPane.showConfirmDialog(null, "Không tìm thấy hóa đơn. Vui lòng chọn lại");
                if(button == JOptionPane.NO_OPTION)
                    System.exit(0);
            }
       }   
    }//GEN-LAST:event_jDeleteActionPerformed

    private void jtHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtHDMouseClicked
        // TODO add your handling code here:
        TableModel model = jtHD.getModel();
        int index = jtHD.getSelectedRow();
        HOADON hd = new HOADON();
        
        //lấy giá trị từ hàng trong bảng & điền giá trị vào từng jLabel trong HOADON
        hd.jMaHD.setText(model.getValueAt(index, 0).toString());
        hd.jMaNV.setText(model.getValueAt(index, 1).toString());
        hd.jMaPN.setText(model.getValueAt(index, 2).toString());
        hd.jMaP.setText(model.getValueAt(index, 3).toString());
        hd.jNgayDen.setText(model.getValueAt(index, 6).toString());
        hd.jNgayRoi.setText(model.getValueAt(index, 7).toString());
        
        
        HOADONTHANHTOAN_BUS hdb = new HOADONTHANHTOAN_BUS ();
        
         // Tính tiền phòng
        int tp = hdb.TIEN_PHONG(Integer.parseInt(hd.jMaHD.getText()));
        hd.jTIENPHONG.setText(Integer.toString(tp));
        // Tiền dịch vụ
        int tdv = hdb.TIEN_DICHVU(Integer.parseInt(hd.jMaHD.getText()));
        hd.jTIENDV.setText(Integer.toString(tdv));
        //Tiền món ăn
        int tma = hdb.TIEN_MONAN(Integer.parseInt(hd.jMaHD.getText()));
        hd.jTIENMA.setText(Integer.toString(tma));
        //Tiền đền bù
        int tdb = hdb.TIEN_DENBU(Integer.parseInt(hd.jMaHD.getText()));
        hd.jTIENDB.setText(Integer.toString(tdb));
        //Tiền giảm
        int tg = hdb.TIEN_GIAM(Integer.parseInt(hd.jMaHD.getText()));
        hd.jTIENGIAM.setText(Integer.toString(tg));
        hd.setVisible(true);
    }//GEN-LAST:event_jtHDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOADONTHANHTOAN_DTO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOADONTHANHTOAN_DTO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOADONTHANHTOAN_DTO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOADONTHANHTOAN_DTO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QUANLIHOADONTHANHTOAN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jDelete;
    private javax.swing.JPanel jHoaDon;
    private javax.swing.JTextField jMaPhong;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSearch;
    private javax.swing.JLabel jTitle;
    public static javax.swing.JTable jtHD;
    // End of variables declaration//GEN-END:variables
}
