/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.BUS_DANGNHAP;
import BUS.BUS_LOAIPHONG;
import BUS.BUS_PHONG;
import DTO.LOAIPHONG;
import DTO.PHONG;
import DTO.TAIKHOAN;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Admin
 */
public class QUANLIPHONG extends javax.swing.JPanel {

    /**
     * Creates new form QUANLIPHONG
     */
    public QUANLIPHONG() {
        initComponents();
        ShowData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jBThem = new javax.swing.JButton();
        jBSua = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBLoc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CalendarNR = new com.toedter.calendar.JDateChooser();
        CalendarND = new com.toedter.calendar.JDateChooser();
        jbLoai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtQLP = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(34, 49, 63));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(1, 50, 67));
        jPanel2.setPreferredSize(new java.awt.Dimension(260, 50));

        jBThem.setBackground(new java.awt.Color(247, 202, 24));
        jBThem.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jBThem.setForeground(new java.awt.Color(1, 50, 67));
        jBThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_plus_math_20px.png"))); // NOI18N
        jBThem.setText("Thêm");
        jBThem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBThemActionPerformed(evt);
            }
        });

        jBSua.setBackground(new java.awt.Color(247, 202, 24));
        jBSua.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jBSua.setForeground(new java.awt.Color(1, 50, 67));
        jBSua.setText("Sửa");
        jBSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSuaActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(1, 50, 67));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(247, 202, 24));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUẢN LÍ PHÒNG");

        jBLoc.setBackground(new java.awt.Color(247, 202, 24));
        jBLoc.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jBLoc.setForeground(new java.awt.Color(1, 50, 67));
        jBLoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_plus_math_20px.png"))); // NOI18N
        jBLoc.setText("Lọc");
        jBLoc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLocActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 202, 24));
        jLabel1.setText("Ngày rời");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(247, 202, 24));
        jLabel3.setText("Ngày đến");

        jbLoai.setBackground(new java.awt.Color(247, 202, 24));
        jbLoai.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jbLoai.setForeground(new java.awt.Color(1, 50, 67));
        jbLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_plus_math_20px.png"))); // NOI18N
        jbLoai.setText("Loại Phòng");
        jbLoai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CalendarND, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CalendarNR, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jBLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbLoai, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jBThem, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBSua, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CalendarND, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CalendarNR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBThem)
                        .addComponent(jBSua, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbLoai))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 120));

        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jtQLP.setBackground(new java.awt.Color(1, 50, 67));
        jtQLP.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtQLP.setForeground(new java.awt.Color(247, 202, 24));
        jtQLP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Phòng", "Tình Trạng", "Mã Loại Phòng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtQLP.setGridColor(new java.awt.Color(0, 90, 134));
        jtQLP.setShowGrid(true);
        jtQLP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtQLPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtQLP);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 770, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtQLPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtQLPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtQLPMouseClicked

    private void jBSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSuaActionPerformed
        String map = null, tinhtrang = null, maloaip = null;
        UPDATEDPHONG up = new UPDATEDPHONG ();
        PHONG p = new PHONG ();
     
        BUS_PHONG bp = new BUS_PHONG();
        try {
            TableModel model = jtQLP.getModel();
            int index = jtQLP.getSelectedRow();
            
            map = model.getValueAt(index, 0).toString();
            tinhtrang = model.getValueAt(index, 1).toString();
            maloaip = model.getValueAt(index, 2).toString();
            
            up.setVisible(true);
            
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn phòng");
            up.setVisible(false);
        }
        
        up.jtfmap.setText(map);
        up.jtfttrp.setText(tinhtrang);
        up.jtfmalp.setText(maloaip);
        

        
        
    }//GEN-LAST:event_jBSuaActionPerformed

    private void jBThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBThemActionPerformed
        // TODO add your handling code here:
        THEMPHONG tp = new THEMPHONG ();
        tp.setVisible(true);
    }//GEN-LAST:event_jBThemActionPerformed

    private void jBLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLocActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat std = new SimpleDateFormat ("dd-MM-YYYY");
        if (CalendarND.getDate()==null && CalendarNR.getDate()== null)
        {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn ngày");
        }
        else if (CalendarND.getDate() == null)
        {
            JOptionPane.showMessageDialog(null, "Ngày đến đang rỗng");
        }
        else if (CalendarNR.getDate()==null)
        {
            JOptionPane.showMessageDialog(null, "Ngày rời đang rỗng");
        }
        else
        {
            String ND = std.format(CalendarND.getDate());
            String NR = std.format(CalendarNR.getDate());
            FilterPhong(ND,NR);
        }
    }//GEN-LAST:event_jBLocActionPerformed

    private void jbLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoaiActionPerformed
        // TODO add your handling code here:
        DSLOAIPHONG lp = new DSLOAIPHONG();
        lp.setVisible(true);
        
    }//GEN-LAST:event_jbLoaiActionPerformed
    
    public static void ShowData () {
        List <PHONG> lp = new ArrayList <PHONG> ();
        BUS_PHONG bp = new BUS_PHONG ();
        Component rootpane = null;
        lp = bp.BUS_LoadPhong();
        if (lp != null)
        {
            DefaultTableModel model = new DefaultTableModel();
            model = (DefaultTableModel) jtQLP.getModel();
            model.setRowCount(0);
            for(int i =0; i<lp.size(); i++)
            {
                model.addRow(new Object [] {lp.get(i).getMaphong(), lp.get(i).getTinhtrang(), lp.get(i).getLoaiphong()});
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootpane, "Không có dữ liệu hiển thị");
        }
    }
        
    public void FilterPhong (String ND, String NR) {
        List <PHONG> lp = new ArrayList <PHONG> ();
        BUS_PHONG bp = new BUS_PHONG ();
        Component rootpane = null;
        lp = bp.FilterPhong(ND,NR);
        if (lp != null)
        {
            DefaultTableModel model = new DefaultTableModel();
            model = (DefaultTableModel) jtQLP.getModel();
            model.setRowCount(0);
            for(int i =0; i<lp.size(); i++)
            {
                model.addRow(new Object [] {lp.get(i).getMaphong(), lp.get(i).getTinhtrang(), lp.get(i).getLoaiphong()});
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootpane, "Không có dữ liệu hiển thị");
        }
        
    }
    
    

       

    
    
    
 {
        
        
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser CalendarND;
    private com.toedter.calendar.JDateChooser CalendarNR;
    private javax.swing.JButton jBLoc;
    private javax.swing.JButton jBSua;
    private javax.swing.JButton jBThem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbLoai;
    private static javax.swing.JTable jtQLP;
    // End of variables declaration//GEN-END:variables
}
