/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BUS.CSVC_BUS;
import DTO.CSVC;
import static GUI.QUANLICSVC.jTable1;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class QUANLICSVC extends javax.swing.JPanel {

    /**
     * Creates new form QUANLICSVC
     */
    public QUANLICSVC() {
        initComponents();
        showCSVC();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtffind = new javax.swing.JTextField();
        jbFind = new javax.swing.JButton();
        jBThem = new javax.swing.JButton();
        jBXoa = new javax.swing.JButton();
        jBSua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(1, 50, 67));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 202, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ CƠ SỞ VẬT CHẤT");

        jtffind.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtffind.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtffind.setText("Tên cơ sở vật chất");

        jbFind.setBackground(new java.awt.Color(247, 202, 24));
        jbFind.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbFind.setForeground(new java.awt.Color(1, 50, 67));
        jbFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_search_20px.png"))); // NOI18N
        jbFind.setText("Tìm kiếm");
        jbFind.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbFind.setMaximumSize(new java.awt.Dimension(113, 30));
        jbFind.setMinimumSize(new java.awt.Dimension(120, 30));
        jbFind.setPreferredSize(new java.awt.Dimension(120, 30));
        jbFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFindActionPerformed(evt);
            }
        });

        jBThem.setBackground(new java.awt.Color(247, 202, 24));
        jBThem.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jBThem.setForeground(new java.awt.Color(1, 50, 67));
        jBThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_plus_math_20px.png"))); // NOI18N
        jBThem.setText("Thêm");
        jBThem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBThemActionPerformed(evt);
            }
        });

        jBXoa.setBackground(new java.awt.Color(247, 202, 24));
        jBXoa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jBXoa.setForeground(new java.awt.Color(1, 50, 67));
        jBXoa.setText("Xóa");
        jBXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBXoaActionPerformed(evt);
            }
        });

        jBSua.setBackground(new java.awt.Color(247, 202, 24));
        jBSua.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jBSua.setForeground(new java.awt.Color(1, 50, 67));
        jBSua.setText("Sửa");
        jBSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jtffind, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtffind, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbFind, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jBSua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBXoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBThem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 42, Short.MAX_VALUE))
        );

        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTable1.setBackground(new java.awt.Color(1, 50, 67));
        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(247, 202, 24));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã cơ sở vật chất", "Tên cơ sở vật chất", "Giá cơ sở vật chất"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 90, 134));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFindActionPerformed
        // TODO add your handling code here:
        CSVC_BUS csvc = new CSVC_BUS();
        javax.swing.table.DefaultTableModel mode;
        mode = (javax.swing.table.DefaultTableModel)this.jTable1.getModel();
        CSVC cs = new CSVC();
        if(csvc.findCSVCByName(jtffind.getText())){
            cs = csvc.getCSVCByName(jtffind.getText());
            mode.setNumRows(0);
            mode.addRow(new Object[]{cs.getMACSVC(),cs.getTENCSVC(), cs.getGIACSVC()});
        }
        else if(jTable1.getSelectedRow() != -1){
            int column = 1;
            int row = jTable1.getSelectedRow();
            String find = jTable1.getValueAt(row,column).toString();
            cs = csvc.getCSVCByName(find);
            mode.setNumRows(0);
            mode.addRow(new Object[]{cs.getMACSVC(),cs.getTENCSVC(), cs.getGIACSVC()});
        }
        else{
            int button = JOptionPane.showConfirmDialog(null,"Không tìm thấy khách hàng. Vui lòng nhập lại" );
            if(button == JOptionPane.NO_OPTION)
            System.exit(0);
        }
    }//GEN-LAST:event_jbFindActionPerformed

    private void jBThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBThemActionPerformed
        // TODO add your handling code here:
        ThemCoSoVatChat csvc = new ThemCoSoVatChat();
        csvc.setVisible(true);
    }//GEN-LAST:event_jBThemActionPerformed

    private void jBXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBXoaActionPerformed
        // TODO add your handling code here:
        javax.swing.table.DefaultTableModel mode;
        mode = (javax.swing.table.DefaultTableModel)this.jTable1.getModel();
        CSVC_BUS cs = new CSVC_BUS();
        Component rootPane = null;
        int column = 1;
        CSVC csvc = new CSVC();
        if(cs.findCSVCByName(jtffind.getText())){
            csvc = cs.getCSVCByName(jtffind.getText());
            mode.setNumRows(0);
            mode.addRow(new Object[]{csvc.getMACSVC(),csvc.getTENCSVC(),csvc.getGIACSVC()});
            int buttonoption = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắc muốn xóa?");
            if(buttonoption == JOptionPane.YES_OPTION){
                boolean rs = cs.deleteCSVC(jtffind.getText());
                mode.removeRow(0);
                if(rs == true)
                JOptionPane.showMessageDialog(rootPane,"Xóa khách hàng thành công");
                else
                JOptionPane.showMessageDialog(rootPane,"Xóa khách hàng thất bại");
            }
        }
        else if(jTable1.getSelectedRow() != -1){
            int row = jTable1.getSelectedRow();
            String find = jTable1.getModel().getValueAt(row, column).toString();
            csvc = cs.getCSVCByName(find);
            mode.setNumRows(0);
            mode.addRow(new Object[]{csvc.getMACSVC(),csvc.getTENCSVC(),csvc.getGIACSVC()});
            int buttonoption = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắc muốn xóa?");
            if(buttonoption == JOptionPane.YES_OPTION){
                boolean rs = cs.deleteCSVC(find);
                mode.removeRow(0);
                if(rs == true)
                JOptionPane.showMessageDialog(rootPane,"Xóa khách hàng thành công");
                else
                JOptionPane.showMessageDialog(rootPane,"Xóa khách hàng thất bại");
            }
        }
        else{
            int button = JOptionPane.showConfirmDialog(rootPane, "Không tìm thấy khách hàng. Vui lòng nhập lại");
            if(button == JOptionPane.NO_OPTION)
            System.exit(0);
        }
    }//GEN-LAST:event_jBXoaActionPerformed

    private void jBSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSuaActionPerformed
        // TODO add your handling code here:
        CSVC_BUS cs = new CSVC_BUS();
        int column = 1;
        CSVC csvc = new CSVC();
        if(cs.findCSVCByName(jtffind.getText())){
            csvc = cs.getCSVCByName(jtffind.getText());
            CapNhatCoSoVatChat capnhat = new CapNhatCoSoVatChat(csvc.getMACSVC(), csvc.getTENCSVC(), csvc.getGIACSVC());
            capnhat.setVisible(true);
        }
        else if( jTable1.getSelectedRow() != -1){
            int row = jTable1.getSelectedRow();
            String find = jTable1.getValueAt(row, column).toString();
            csvc = cs.getCSVCByName(find);
            CapNhatCoSoVatChat capnhat = new CapNhatCoSoVatChat(csvc.getMACSVC(), csvc.getTENCSVC(), csvc.getGIACSVC());
            capnhat.setVisible(true);
        }
        else{
            Component rootPane = null;
            int optionbutton = JOptionPane.showConfirmDialog(rootPane, "Không tìm thấy cơ sở vật chất. Vui lòng nhập lại");
            if(optionbutton == JOptionPane.NO_OPTION)
            System.exit(0);
        }
    }//GEN-LAST:event_jBSuaActionPerformed

    public static void showCSVC(){
        List<CSVC> cs = new ArrayList<>();
        CSVC_BUS csvc = new CSVC_BUS();
        cs = csvc.getCSVC();
        Component rootPane = null; 
        if(cs != null){
            javax.swing.table.DefaultTableModel mode;
            mode = (javax.swing.table.DefaultTableModel)jTable1.getModel();
            mode.setNumRows(0);
            for(int i = 0; i < cs.size();i++){
                mode.addRow(new Object[]{cs.get(i).getMACSVC(),cs.get(i).getTENCSVC(), cs.get(i).getGIACSVC()});
            }
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Không có dữ liệu để hiển thị");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSua;
    private javax.swing.JButton jBThem;
    private javax.swing.JButton jBXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    protected static javax.swing.JTable jTable1;
    private javax.swing.JButton jbFind;
    private javax.swing.JTextField jtffind;
    // End of variables declaration//GEN-END:variables
}
