/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.KHACHHANG_BUS;
import BUS.PHIEUNHANPHONG_BUS;
import DTO.KHACHHANG;
import DTO.PHIEUNHANPHONG;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class QuanLyThongTinNhanPhong extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyThongTinNhanPhong
     */
    public QuanLyThongTinNhanPhong() {
        initComponents();
        showListPhieuNhanPhong();
    }
    public static void showListPhieuNhanPhong(){
        PHIEUNHANPHONG_BUS pnp = new PHIEUNHANPHONG_BUS();
        List<PHIEUNHANPHONG> np = new ArrayList<>();
        np = pnp.getListPhieuNhanPhong();
        if(np != null){
            DefaultTableModel mode = new DefaultTableModel();
            mode = (DefaultTableModel)jTable1.getModel();
            mode.setNumRows(0);
            for(int i = 0; i < np.size(); i++){
                mode.addRow(new Object[]{np.get(i).getMAPHIEUNHAN(), 
                    np.get(i).getTENKH(), np.get(i).getMAPHONG(), np.get(i).getTENNV(), 
                    np.get(i).getSONGUOIDIKEM(),np.get(i).getNGAYDEN(), np.get(i).getNGAYROI()
                });
            }
        }else
            JOptionPane.showMessageDialog(null, "Không có dữ liệu để hiển thị");

        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtffind = new javax.swing.JTextField();
        jbFind = new javax.swing.JButton();
        jBThem = new javax.swing.JButton();
        jBXoa = new javax.swing.JButton();
        jBSua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(1, 50, 67));
        jPanel1.setForeground(new java.awt.Color(247, 202, 24));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 202, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ PHIẾU NHẬN PHÒNG");
        jLabel1.setToolTipText("");

        jtffind.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtffind.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtffind.setText("CMND");

        jbFind.setBackground(new java.awt.Color(247, 202, 24));
        jbFind.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_search_20px.png"))); // NOI18N
        jbFind.setText("Tìm kiếm");
        jbFind.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbFind.setMaximumSize(new java.awt.Dimension(113, 30));
        jbFind.setMinimumSize(new java.awt.Dimension(120, 30));
        jbFind.setPreferredSize(new java.awt.Dimension(120, 30));
        jbFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFindActionPerformed(evt);
            }
        });

        jBThem.setBackground(new java.awt.Color(247, 202, 24));
        jBThem.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jBThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_plus_math_20px.png"))); // NOI18N
        jBThem.setText("Thêm");
        jBThem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBThemActionPerformed(evt);
            }
        });

        jBXoa.setBackground(new java.awt.Color(247, 202, 24));
        jBXoa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jBXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_delete_20px_1.png"))); // NOI18N
        jBXoa.setText("Xóa");
        jBXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBXoaActionPerformed(evt);
            }
        });

        jBSua.setBackground(new java.awt.Color(247, 202, 24));
        jBSua.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jBSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_update_20px_1.png"))); // NOI18N
        jBSua.setText("Sửa");
        jBSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jtffind, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtffind, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbFind, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBThem)
                        .addComponent(jBXoa)
                        .addComponent(jBSua)))
                .addGap(0, 42, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        jTable1.setBackground(new java.awt.Color(1, 50, 67));
        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(247, 202, 24));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu nhận", "Họ tên", "Mã phòng", "Tên nhân viên", "Số người đi kèm", "Ngày đến", "Ngày rời"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("");
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 740, 340));
    }// </editor-fold>//GEN-END:initComponents

    private void jbFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFindActionPerformed
        // TODO add your handling code here:
        PHIEUNHANPHONG_BUS pnp = new PHIEUNHANPHONG_BUS();
        if(pnp.findPhieuNhanPhong(jtffind.getText())){
            List<PHIEUNHANPHONG> pn = new ArrayList<>();
            pn = pnp.getListPhieuNhanPhongByCMND(jtffind.getText());
            DefaultTableModel mode = new DefaultTableModel();
            mode = (DefaultTableModel)jTable1.getModel();
            mode.setNumRows(0);
            for(int i = 0; i< pn.size(); i++){
                mode.addRow(new Object[]{pn.get(i).getMAPHIEUNHAN(), pn.get(i).getTENKH(), pn.get(i).getMAPHONG(),
                    pn.get(i).getTENNV(), pn.get(i).getSONGUOIDIKEM(), pn.get(i).getNGAYDEN(), pn.get(i).getNGAYROI()
                });
            }
        }
    }//GEN-LAST:event_jbFindActionPerformed

    private void jBThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBThemActionPerformed
        // TODO add your handling code here:
        KHACHHANG_BUS kh = new KHACHHANG_BUS();
        if(kh.findKhachHang(jtffind.getText())){
            KHACHHANG khachhang = new KHACHHANG();
            khachhang = kh.getKhachHangByCMND(jtffind.getText());
            ThemPhieuNhanPhong tpnp = new ThemPhieuNhanPhong(khachhang);
            tpnp.setVisible(true);
        }
        else{
            ThemKhachHang tkh = new ThemKhachHang(jtffind.getText());
            tkh.setVisible(true);
            tkh.addWindowListener(new WindowAdapter(){
                public void windowClosed(WindowEvent e){
                    ThemPhieuNhanPhong pnp = new ThemPhieuNhanPhong(kh.getKhachHangByCMND(jtffind.getText()));
                    pnp.setVisible(true);
                }
            });
        }      
    }//GEN-LAST:event_jBThemActionPerformed

    private void jBXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBXoaActionPerformed
        // TODO add your handling code here:
        PHIEUNHANPHONG_BUS pnp = new PHIEUNHANPHONG_BUS();
        int button = JOptionPane.showConfirmDialog(null,"Bạn có chắc chắn muốn xóa phiếu nhận phòng?");
        if(button == JOptionPane.YES_OPTION){
            if(jTable1.getRowCount() > 1){
                if(jTable1.getSelectedRow() != -1){
                    int find = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(),0).toString());
                    boolean rs = pnp.deletePhieuNhanPhong(find);
                    if(rs == true){
                        JOptionPane.showMessageDialog(null,"Xóa phiếu nhận phòng thành công");
                        showListPhieuNhanPhong();
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Xóa phiếu nhận phòng thành công");
                        showListPhieuNhanPhong();
                    }
                }
                else 
                    JOptionPane.showMessageDialog(null,"Vui lòng chọn phiếu nhận phòng cần xóa");
            }
            else{
                boolean rs = pnp.deletePhieuNhanPhong(Integer.parseInt(jTable1.getValueAt(0,0).toString()));
                if(rs == true){
                    JOptionPane.showMessageDialog(null, "Xóa phiếu nhận phòng thành công");
                    showListPhieuNhanPhong();
                }else{
                    JOptionPane.showMessageDialog(null, "Xóa phiếu nhận phòng thất bại");
                    showListPhieuNhanPhong();
                }      
            }
        }
    }//GEN-LAST:event_jBXoaActionPerformed

    private void jBSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSuaActionPerformed
        // TODO add your handling code here:
        PHIEUNHANPHONG_BUS pnp = new PHIEUNHANPHONG_BUS();
        if(jTable1.getRowCount() > 1){
            if(jTable1.getSelectedRow() != -1){
                int find = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(),0).toString());
                PHIEUNHANPHONG np = pnp.getTTPhieuNhanPhong(find);
                CapNhatPhieuNhanPhong cnnp = new CapNhatPhieuNhanPhong(np);
                cnnp.setVisible(true);
            }
            else
                JOptionPane.showMessageDialog(null, "Vui lòng chọn phiếu nhận phòng để cập nhật");
        }else{
            int find = Integer.parseInt(jTable1.getValueAt(0,0).toString());
            PHIEUNHANPHONG np = pnp.getTTPhieuNhanPhong(find);
            CapNhatPhieuNhanPhong cnnp = new CapNhatPhieuNhanPhong(np);
            cnnp.setVisible(true);
        }
            
    }//GEN-LAST:event_jBSuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSua;
    private javax.swing.JButton jBThem;
    private javax.swing.JButton jBXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    private javax.swing.JButton jbFind;
    private javax.swing.JTextField jtffind;
    // End of variables declaration//GEN-END:variables
}
