/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.CSVC_BUS;
import DTO.HOADON_CSVC_DTO;
import DAO.DAO_HOADON_CSVC;
import BUS.HOADON_CSVC_BUS;
import DTO.CSVC;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class THEM_HOADON_CSVC extends javax.swing.JFrame {

    /**
     * Creates new form THEM_HOADON_CSVC
     */
    
    
    public THEM_HOADON_CSVC() {
        initComponents();
        ShowInfo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jcbCSVC = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jInsert = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jSOLUONG = new javax.swing.JSpinner();
        jHIENTHI = new javax.swing.JButton();
        jMAHD = new javax.swing.JTextField();
        jTHANHTIEN = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jGia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(1, 50, 67));
        jPanel.setPreferredSize(new java.awt.Dimension(767, 454));

        jcbCSVC.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcbCSVC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCSVCActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(247, 202, 24));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 202, 24));
        jLabel1.setText("CƠ SỞ VẬT CHẤT");

        jLabel2.setBackground(new java.awt.Color(247, 202, 24));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(247, 202, 24));
        jLabel2.setText("SỐ LƯỢNG");

        jInsert.setBackground(new java.awt.Color(247, 202, 24));
        jInsert.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jInsert.setForeground(new java.awt.Color(1, 50, 67));
        jInsert.setText("THÊM CSVC");
        jInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(247, 202, 24));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(247, 202, 24));
        jLabel3.setText("THÊM CƠ SỞ VẬT CHẤT");

        jLabel4.setBackground(new java.awt.Color(247, 202, 24));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(247, 202, 24));
        jLabel4.setText("MÃ HÓA ĐƠN");

        jLabel6.setBackground(new java.awt.Color(247, 202, 24));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(247, 202, 24));
        jLabel6.setText("THÀNH TIỀN");

        jTable.setBackground(new java.awt.Color(247, 202, 24));
        jTable.setForeground(new java.awt.Color(1, 50, 67));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã CSVC", "Mã Hóa đơn", "Số lượng", "Thành tiền"
            }
        ));
        jTable.setShowGrid(true);
        jScrollPane1.setViewportView(jTable);

        jSOLUONG.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jHIENTHI.setBackground(new java.awt.Color(247, 202, 24));
        jHIENTHI.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jHIENTHI.setForeground(new java.awt.Color(1, 50, 67));
        jHIENTHI.setText("HIỂN THỊ DỮ LIỆU");
        jHIENTHI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHIENTHIActionPerformed(evt);
            }
        });

        jMAHD.setEditable(false);
        jMAHD.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jTHANHTIEN.setEditable(false);
        jTHANHTIEN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel7.setBackground(new java.awt.Color(247, 202, 24));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(247, 202, 24));
        jLabel7.setText("GIÁ");

        jGia.setEditable(false);
        jGia.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(292, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(210, 210, 210))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                            .addComponent(jHIENTHI)
                            .addGap(18, 18, 18)
                            .addComponent(jInsert)
                            .addGap(27, 27, 27))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2))
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelLayout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jcbCSVC, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSOLUONG, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(10, 10, 10))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jMAHD, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap()))))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTHANHTIEN, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jGia, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(77, 77, 77)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMAHD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbCSVC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSOLUONG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jGia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTHANHTIEN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jHIENTHI)
                            .addComponent(jInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ShowHoaDonCSVC()
    {
        List<HOADON_CSVC_DTO> hds = new ArrayList<HOADON_CSVC_DTO>();
        HOADON_CSVC_BUS hd = new HOADON_CSVC_BUS();
        Component frame = null;
        
        int Ma_HD = Integer.parseInt(jMAHD.getText());
        
        if(hd.getListCSVCbyMaHD(Ma_HD) != null)
        {
            javax.swing.table.DefaultTableModel mode;
            mode = (javax.swing.table.DefaultTableModel) this.jTable.getModel();
            mode.setNumRows(0);
            hds = hd.getListCSVCbyMaHD(Ma_HD);
            for(int i=0; i < hds.size(); i++)
                mode.addRow(new Object[]{hds.get(i).getMACSVC(),hds.get(i).getMAHD(),hds.get(i).getSOLUONG(),hds.get(i).getTHANHTIEN()});
        }
        else
            JOptionPane.showMessageDialog(frame, "Không có dữ liệu để hiển thị");
    }
    
    public void ShowInfo()
    {
        CSVC_BUS csvc = new CSVC_BUS();
        List<CSVC> csvcs = new ArrayList<CSVC>();
        
        csvcs = csvc.getCSVC();
        for(int i=0; i < csvcs.size(); i++)
            jcbCSVC.addItem(csvcs.get(i).getTENCSVC());
    }
    
    public void gia (String value)
    {
        
        CSVC_BUS csvcb = new CSVC_BUS();
        CSVC csvc = new CSVC();
        csvc = csvcb.getCSVCByName(value);
        String gia = Integer.toString(csvc.getGIACSVC());
        jGia.setText(gia);
        
    }
    
    private void jInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertActionPerformed
        // TODO add your handling code here:
        CSVC_BUS csvc = new CSVC_BUS();
        List<CSVC> csvcs = new ArrayList<CSVC>();
        HOADON_CSVC_BUS hds = new HOADON_CSVC_BUS();
        HOADON_CSVC_DTO hd = new HOADON_CSVC_DTO();
        CSVC temp = new CSVC();
        String ten = (String)jcbCSVC.getSelectedItem();
        temp = csvc.getCSVCByName(ten);
        int sl = Integer.parseInt(jSOLUONG.getValue().toString());
        
        hd.setMAHD(Integer.parseInt(jMAHD.getText()));
        hd.setMACSVC(temp.getMACSVC());
        hd.setSOLUONG(sl);
        hd.setTHANHTIEN(temp.getGIACSVC() * sl);
        int gia =temp.getGIACSVC() * sl;
        jTHANHTIEN.setText(Integer.toString(gia));
        
        Component frame = null;
        int buttonoption = JOptionPane.showConfirmDialog(frame,"Xác nhận thêm hóa đơn CSVC ?");
        if(buttonoption == JOptionPane.YES_OPTION)
        {
            if(hds.INSERT_HOADON_CSVC(hd))
                JOptionPane.showMessageDialog(frame, "Thêm hóa đơn CSVC thành công");
            else
                JOptionPane.showMessageDialog(frame, "Thêm hóa đơn CSVC thất bại");
        }
        else
            JOptionPane.showMessageDialog(frame, "Thêm hóa đơn CSVC thất bại");
    }//GEN-LAST:event_jInsertActionPerformed

    private void jHIENTHIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHIENTHIActionPerformed
        // TODO add your handling code here:
        ShowHoaDonCSVC();

    }//GEN-LAST:event_jHIENTHIActionPerformed

    private void jcbCSVCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCSVCActionPerformed
        // TODO add your handling code here:
        gia(jcbCSVC.getSelectedItem().toString());
    }//GEN-LAST:event_jcbCSVCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(THEM_HOADON_CSVC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(THEM_HOADON_CSVC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(THEM_HOADON_CSVC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(THEM_HOADON_CSVC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new THEM_HOADON_CSVC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jGia;
    private javax.swing.JButton jHIENTHI;
    private javax.swing.JButton jInsert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JTextField jMAHD;
    private javax.swing.JPanel jPanel;
    private javax.swing.JSpinner jSOLUONG;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTHANHTIEN;
    private javax.swing.JTable jTable;
    private javax.swing.JComboBox<String> jcbCSVC;
    // End of variables declaration//GEN-END:variables
}
