/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.BANGKE_DV_BUS;
import DTO.BANGKE_DV_DTO;
import BUS.BUS_DICHVU;
import DTO.DICHVU;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class THEM_BANGKE_DV extends javax.swing.JFrame {

    /**
     * Creates new form THEM_BANGKE_DV
     */
  
    
    public THEM_BANGKE_DV() {
        initComponents(); 
        ShowInfo();
        this.dispose();
        
   
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        jPanel = new javax.swing.JPanel();
        jcbDV = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jInsert = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtBKDV = new javax.swing.JTable();
        jMAHD = new javax.swing.JTextField();
        jTHANHTIEN = new javax.swing.JTextField();
        jShow = new javax.swing.JButton();
        Ngay = new com.toedter.calendar.JDateChooser();

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(1, 50, 67));
        jPanel.setPreferredSize(new java.awt.Dimension(767, 454));

        jcbDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbDVMouseClicked(evt);
            }
        });
        jcbDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDVActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 202, 24));
        jLabel1.setText("DỊCH VỤ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(247, 202, 24));
        jLabel2.setText("NGÀY SỬ DỤNG");

        jInsert.setBackground(new java.awt.Color(247, 202, 24));
        jInsert.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jInsert.setForeground(new java.awt.Color(1, 50, 67));
        jInsert.setText("ĐẶT DỊCH VỤ");
        jInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(247, 202, 24));
        jLabel3.setText("ĐẶT DỊCH VỤ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(247, 202, 24));
        jLabel4.setText("MÃ HÓA ĐƠN");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(247, 202, 24));
        jLabel6.setText("THÀNH TIỀN");

        jtBKDV.setBackground(new java.awt.Color(247, 202, 24));
        jtBKDV.setForeground(new java.awt.Color(1, 50, 67));
        jtBKDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Dịch vụ", "Mã Hóa đơn", "Ngày sử dụng", "Thành tiền"
            }
        ));
        jtBKDV.setGridColor(new java.awt.Color(1, 50, 67));
        jtBKDV.setShowGrid(true);
        jScrollPane1.setViewportView(jtBKDV);

        jMAHD.setEditable(false);
        jMAHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAHDActionPerformed(evt);
            }
        });

        jTHANHTIEN.setEditable(false);
        jTHANHTIEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTHANHTIENActionPerformed(evt);
            }
        });

        jShow.setBackground(new java.awt.Color(247, 202, 24));
        jShow.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jShow.setForeground(new java.awt.Color(1, 50, 67));
        jShow.setText("Hiển thị dữ liệu");
        jShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(39, 39, 39)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jcbDV, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jMAHD, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTHANHTIEN, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ngay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addComponent(jShow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(jInsert)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(294, 294, 294))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(86, 86, 86)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMAHD, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbDV, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ngay, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTHANHTIEN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jShow, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertActionPerformed
        // TODO add your handling code here:
        BANGKE_DV_BUS bks = new BANGKE_DV_BUS();
        BANGKE_DV_DTO bk = new BANGKE_DV_DTO();
        BUS_DICHVU dv = new BUS_DICHVU();
        
        SimpleDateFormat std = new SimpleDateFormat("dd-MM-YY");
        String date = std.format(Ngay.getDate());
        
        DICHVU temp = new DICHVU();        
        String ten = jcbDV.getSelectedItem().toString();
        temp.setMADV(dv.BUS_getDVbyten(ten).getMADV());
        
        
        bk.setMAHD(Integer.parseInt(jMAHD.getText()));
        bk.setMADV(temp.getMADV());
        bk.setNGAY(date);
        bk.setTHANHTIEN(Integer.parseInt(jTHANHTIEN.getText()));
        
        Component frame = null;
        
        int buttonoption = JOptionPane.showConfirmDialog(frame,"Xác nhận đặt dịch vụ ?");
        
        if(buttonoption == JOptionPane.YES_OPTION)
        {
            if(bks.INSERT_BANGKE_DV(bk)==true)
            {
                ShowBangKeDV();
                JOptionPane.showMessageDialog(frame, "Đặt dịch vụ thành công");
            }
            else
            {
                JOptionPane.showMessageDialog(frame, "Đặt dịch vụ thất bại");
            }
        }
        else
            JOptionPane.showMessageDialog(frame, "Đặt dịch vụ thất bại");
        
        
    }//GEN-LAST:event_jInsertActionPerformed

    private void jcbDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDVActionPerformed
        // TODO add your handling code here:
        THANHTIEN(jcbDV.getSelectedItem().toString());
    }//GEN-LAST:event_jcbDVActionPerformed

    private void jMAHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMAHDActionPerformed

    private void jTHANHTIENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTHANHTIENActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTHANHTIENActionPerformed

    private void jShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowActionPerformed
        // TODO add your handling code here:
        ShowBangKeDV();
    }//GEN-LAST:event_jShowActionPerformed

    private void jcbDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbDVMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jcbDVMouseClicked

     public static void ShowBangKeDV()
    {

        List<BANGKE_DV_DTO> bks = new ArrayList<BANGKE_DV_DTO>();
        BANGKE_DV_BUS bk = new BANGKE_DV_BUS();
        Component frame = null;
        
        
        if(jMAHD.getText().equals("") == true)
        {
            JOptionPane.showMessageDialog(frame,"Vui lòng nhập mã HD");
        }
        else        
        {
            bks = bk.getListBangKeDVbyMAHD(Integer.parseInt(jMAHD.getText()));

            if(bks != null)
            {
                DefaultTableModel model = new DefaultTableModel ();
                model = (DefaultTableModel) jtBKDV.getModel();
                model.setNumRows(0);
                for (int i=0; i < bks.size(); i++)
                model.addRow(new Object[]{bks.get(i).getMADV(),bks.get(i).getMAHD(),bks.get(i).getNGAY(),bks.get(i).getTHANHTIEN()});
            }
            else
                JOptionPane.showMessageDialog(frame, "Không có dữ liệu để hiển thị");
        }
    }
    
    
    public void ShowInfo()
    {
        BUS_DICHVU dv = new BUS_DICHVU();
        List<DICHVU> dvs = new ArrayList <DICHVU> ();
        dvs = dv.BUS_LoadData();
        for (int i = 0; i < dvs.size(); i++)
            jcbDV.addItem(dvs.get(i).getTENDV());
    }
    public void THANHTIEN(String value)
    {
        BUS_DICHVU bdv = new BUS_DICHVU();
        DICHVU dv = new DICHVU();
        dv =bdv.BUS_getDVbyten(value);
        String gia = Integer.toString(dv.getGIADV());
        jTHANHTIEN.setText(gia);
    }
    
    
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(THEM_BANGKE_DV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(THEM_BANGKE_DV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(THEM_BANGKE_DV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(THEM_BANGKE_DV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new THEM_BANGKE_DV().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Ngay;
    private javax.swing.JButton jInsert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JTextField jMAHD;
    private static javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jShow;
    public static javax.swing.JTextField jTHANHTIEN;
    public static javax.swing.JComboBox<String> jcbDV;
    public static javax.swing.JTable jtBKDV;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    // End of variables declaration//GEN-END:variables
}
