/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.NHANVIEN_BUS;
import BUS.PHIEUDATTRUOC_BUS;
import DTO.LOAIPHONG;
import Class.NHANVIEN_TT;
import DTO.PHIEUDATTRUOC;
import COMBOBOX.PHONGTRONG;
import DTO.KHACHHANG;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Random;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author HP
 */
public class ThemPhieuDatTruoc extends javax.swing.JFrame {

    /**
     * Creates new form ThemPhieuDatTruoc
     */
    public ThemPhieuDatTruoc() {
        initComponents();
    }

    public ThemPhieuDatTruoc(KHACHHANG makh) {
        initComponents();
        jtfmakh.setText(String.valueOf(makh.getMAKH()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbthem = new javax.swing.JButton();
        jtfmakh = new javax.swing.JTextField();
        jbhuy = new javax.swing.JButton();
        jngayden = new com.toedter.calendar.JDateChooser();
        jngayroi = new com.toedter.calendar.JDateChooser();
        jmanv = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jloaiphong = new javax.swing.JComboBox<LOAIPHONG>();
        jphong = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jsonguoidikem = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(1, 50, 67));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 202, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÊM PHIẾU ĐẶT TRƯỚC");

        jPanel1.setBackground(new java.awt.Color(1, 50, 67));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(247, 202, 24));
        jLabel2.setText("Mã phòng");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(247, 202, 24));
        jLabel3.setText("Mã khách hàng");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(247, 202, 24));
        jLabel4.setText("Tên nhân viên");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(247, 202, 24));
        jLabel5.setText("Ngày đến");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(247, 202, 24));
        jLabel6.setText("Ngày rời");

        jbthem.setBackground(new java.awt.Color(247, 202, 24));
        jbthem.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jbthem.setForeground(new java.awt.Color(1, 50, 67));
        jbthem.setText("Thêm");
        jbthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbthemActionPerformed(evt);
            }
        });

        jtfmakh.setEditable(false);
        jtfmakh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtfmakh.setEnabled(false);

        jbhuy.setBackground(new java.awt.Color(247, 202, 24));
        jbhuy.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jbhuy.setForeground(new java.awt.Color(1, 50, 67));
        jbhuy.setText("Hủy");
        jbhuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbhuyActionPerformed(evt);
            }
        });

        Date date = new Date();
        jngayden.setDate(date);
        jngayden.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jngayroi.setDate(date);
        jngayroi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jmanv.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        NHANVIEN_BUS nhanvien = new NHANVIEN_BUS();
        List<NHANVIEN_TT> nv = new ArrayList<>();
        nv = nhanvien.getTTNhanVien();
        for(int i = 0; i< nv.size(); i++){
            jmanv.addItem(nv.get(i));
        }
        jmanv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmanvActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(247, 202, 24));
        jLabel7.setText("Tên loại phòng");

        showdataforjloaiphong();
        jloaiphong.setSelectedItem(null);
        jloaiphong.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jloaiphong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jloaiphongItemStateChanged(evt);
            }
        });
        jloaiphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloaiphongActionPerformed(evt);
            }
        });

        jphong.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(247, 202, 24));
        jLabel8.setText("Số người đi kèm");

        jsonguoidikem.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jbthem, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbhuy, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jphong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jmanv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jngayden, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(jngayroi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jloaiphong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfmakh)
                            .addComponent(jsonguoidikem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(42, 42, 42))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbhuy, jbthem});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jngayden, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jngayroi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jloaiphong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(jphong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfmakh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jmanv, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jsonguoidikem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbthem, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jbhuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbhuy, jbthem});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jloaiphong, jtfmakh});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jngayden, jngayroi});

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void showdataforjloaiphong(){
        PHIEUDATTRUOC_BUS pdt = new PHIEUDATTRUOC_BUS();
        List<LOAIPHONG> lp = new ArrayList<>();
        lp = pdt.getListLoaiPhong();
        for(int i = 0; i < lp.size(); i++){
            jloaiphong.addItem(lp.get(i));
        }

    }
    public void showdataforjphong(){
        PHIEUDATTRUOC_BUS pdt = new PHIEUDATTRUOC_BUS();
        List<Integer> maphong = new ArrayList<>();
        Date date = jngayden.getDate();
        SimpleDateFormat dateformat = new SimpleDateFormat("dd-MM-YYYY");
        String ngayden = dateformat.format(date);
        date = jngayroi.getDate();
        String ngayroi = dateformat.format(date);
        System.out.println(ngayden + " " + ngayroi);
        LOAIPHONG a = (LOAIPHONG)jloaiphong.getSelectedItem();
        maphong = pdt.getListPhongTrong(ngayden, ngayroi,a.getMALOAIPHONG());
        jphong.removeAllItems();
        for(int i = 0; i < maphong.size(); i++){
            this.jphong.addItem(String.valueOf(maphong.get(i)));
        }
        Random rd = new Random();
        int n = maphong.get(rd.nextInt(maphong.size()));
        System.out.println(n);
        jphong.setSelectedItem(String.valueOf(n));
    }
    
    public void showdataforjsonguoidikem(){
        LOAIPHONG lp = (LOAIPHONG)jloaiphong.getSelectedItem();
        int n = lp.getSOLUONGNGUOI();
        jsonguoidikem.removeAllItems();
        for(int i = 1; i < n; i++){
            jsonguoidikem.addItem(String.valueOf(i));
        }
    }
    private void jbhuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbhuyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbhuyActionPerformed

    private void jbthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbthemActionPerformed
        // TODO add your handling code here:
            PHIEUDATTRUOC_BUS pdt = new PHIEUDATTRUOC_BUS();
            PHIEUDATTRUOC dt = new PHIEUDATTRUOC();
            dt.setMAKH(Integer.parseInt(jtfmakh.getText()));
            NHANVIEN_TT nv = (NHANVIEN_TT)jmanv.getSelectedItem();
            dt.setMANV(nv.getMANV());
            dt.setMAPHONG(Integer.parseInt(jphong.getSelectedItem().toString()));
            Date date = jngayden.getDate();
            SimpleDateFormat dateformat = new SimpleDateFormat("dd-MM-YYYY");
            String ngayden = dateformat.format(date);
            dt.setNGAYDEN(ngayden); 
            date = jngayroi.getDate();
            String ngayroi = dateformat.format(date);
            dt.setNGAYROI(ngayroi);
            dt.setSONGUOIDIKEM(Integer.parseInt(jsonguoidikem.getSelectedItem().toString()));
            boolean rs = pdt.addPhieuDatTruoc(dt);
            if(rs == true)
                JOptionPane.showMessageDialog(null, "Thêm phiếu đặt trước thành công");
            else
                JOptionPane.showMessageDialog(null, "Thêm phiếu đặt trước thất bại");
    }//GEN-LAST:event_jbthemActionPerformed

    private void jmanvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmanvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmanvActionPerformed

    private void jloaiphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jloaiphongActionPerformed

    }//GEN-LAST:event_jloaiphongActionPerformed

    private void jloaiphongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jloaiphongItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() == java.awt.event.ItemEvent.SELECTED){
            LOAIPHONG phong = (LOAIPHONG)evt.getItem();
            showdataforjphong();
            showdataforjsonguoidikem();
        }
    }//GEN-LAST:event_jloaiphongItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemPhieuDatTruoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemPhieuDatTruoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemPhieuDatTruoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemPhieuDatTruoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemPhieuDatTruoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbhuy;
    private javax.swing.JButton jbthem;
    private javax.swing.JComboBox<LOAIPHONG> jloaiphong;
    private javax.swing.JComboBox<NHANVIEN_TT> jmanv;
    private com.toedter.calendar.JDateChooser jngayden;
    private com.toedter.calendar.JDateChooser jngayroi;
    private javax.swing.JComboBox<String> jphong;
    private javax.swing.JComboBox<String> jsonguoidikem;
    public static javax.swing.JTextField jtfmakh;
    // End of variables declaration//GEN-END:variables
}
