/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.BANGKE_MONAN_BUS;
import DTO.BANGKE_MONAN_DTO;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.*;
/**
 *
 * @author ADMIN
 */
public class XOA_BANGKE_MA extends javax.swing.JFrame {

    int row = 0;
    /**
     * Creates new form BANGKE_MONAN
     */
    public XOA_BANGKE_MA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jBKMA = new javax.swing.JTable();
        jDelete = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMAHD = new javax.swing.JTextField();
        jMAMON = new javax.swing.JTextField();
        jNgay = new javax.swing.JTextField();
        jTHANHTIEN = new javax.swing.JTextField();
        jSoLuong = new javax.swing.JTextField();
        jShow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(1, 50, 67));

        jBKMA.setBackground(new java.awt.Color(247, 202, 24));
        jBKMA.setForeground(new java.awt.Color(1, 50, 67));
        jBKMA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", null, ""},
                {"", "", "", null, ""},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Dịch vụ", "Mã Hóa đơn", "Ngày sử dụng", "Số lượng", "Thành tiền"
            }
        ));
        jBKMA.setShowGrid(true);
        jBKMA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBKMAMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jBKMA);

        jDelete.setBackground(new java.awt.Color(247, 202, 24));
        jDelete.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jDelete.setForeground(new java.awt.Color(1, 50, 67));
        jDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_delete_20px.png"))); // NOI18N
        jDelete.setText("XÓA");
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(247, 202, 24));
        jLabel9.setText("DANH SÁCH BẢNG KÊ MÓN ĂN");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 202, 24));
        jLabel1.setText("MÓN ĂN");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(247, 202, 24));
        jLabel4.setText("MÃ HÓA ĐƠN");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(247, 202, 24));
        jLabel2.setText("NGÀY SỬ DỤNG");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(247, 202, 24));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("SỐ LƯỢNG");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(247, 202, 24));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("THÀNH TIỀN");

        jMAHD.setEditable(false);

        jMAMON.setEditable(false);

        jNgay.setEditable(false);

        jTHANHTIEN.setEditable(false);

        jSoLuong.setEditable(false);

        jShow.setBackground(new java.awt.Color(247, 202, 24));
        jShow.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jShow.setForeground(new java.awt.Color(1, 50, 67));
        jShow.setText("Hiển thị dữ liệu");
        jShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(194, 194, 194))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addComponent(jLabel7))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jMAHD, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                .addComponent(jMAMON)
                                .addComponent(jNgay)
                                .addComponent(jSoLuong)
                                .addComponent(jTHANHTIEN))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jShow)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                                .addComponent(jDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(101, Short.MAX_VALUE))))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addGap(98, 98, 98)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMAHD, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMAMON, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTHANHTIEN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jShow))
                        .addGap(19, 19, 19))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
        // TODO add your handling code here:
        
        BANGKE_MONAN_DTO bk = new BANGKE_MONAN_DTO();
        bk.setMAMON(Integer.parseInt(jMAMON.getText()));
        bk.setMAHD(Integer.parseInt(jMAHD.getText()));
        bk.setNGAY(jNgay.getText());
        bk.setSOLUONG(Integer.parseInt(jSoLuong.getText()));
        bk.setTHANHTIEN(Integer.parseInt(jTHANHTIEN.getText()));

        Component frame = null;

        if(jMAMON.getText() != null)
        {
            BANGKE_MONAN_BUS bks = new BANGKE_MONAN_BUS();

            int buttonoption = JOptionPane.showConfirmDialog(frame,"Xác nhận xóa bảng kê món ăn ?");
            if(buttonoption == JOptionPane.YES_OPTION)
            {
                boolean rs = bks.DELETE_BANGKE_MONAN(bk);
              
                if(rs==true)
                {
                    DefaultTableModel model = (DefaultTableModel)jBKMA.getModel();
                    model.removeRow(row);
                    JOptionPane.showMessageDialog(frame, "Xóa bảng kê món ăn thành công");
                }
                else
                JOptionPane.showMessageDialog(frame, "Xóa bảng kê món ăn thất bại");
            }
            else
            {
                int button = JOptionPane.showConfirmDialog(frame, "Không tìm thấy bảng kê món ăn");
                if(button == JOptionPane.NO_OPTION)
                System.exit(0);
            }
        }
        else
        JOptionPane.showMessageDialog(frame,"Vui lòng click chọn bảng kê món ăn muốn xóa!");
    }//GEN-LAST:event_jDeleteActionPerformed

    private void jBKMAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBKMAMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jBKMA.getModel();
        row = jBKMA.getSelectedRow();

        jMAMON.setText(model.getValueAt(row, 0).toString());
        jMAHD.setText(model.getValueAt(row, 1).toString());
        jNgay.setText(model.getValueAt(row, 2).toString());
        jSoLuong.setText(model.getValueAt(row, 3).toString());
        jTHANHTIEN.setText(model.getValueAt(row, 4).toString());
    }//GEN-LAST:event_jBKMAMouseClicked

    private void jShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowActionPerformed
        // TODO add your handling code here:
         ShowBangKeMONAN ();
    }//GEN-LAST:event_jShowActionPerformed

    public void ShowBangKeMONAN ()
    {
        List<BANGKE_MONAN_DTO> bks = new ArrayList<BANGKE_MONAN_DTO>();
        BANGKE_MONAN_BUS bk = new BANGKE_MONAN_BUS();
        Component frame = null;
        
        int Ma_HD = Integer.parseInt(jMAHD.getText());
        
        if(bk.getListBKMonAnbyMAHD(Ma_HD) != null)
        {
            javax.swing.table.DefaultTableModel mode;
            mode = (javax.swing.table.DefaultTableModel) this.jBKMA.getModel();
            mode.setNumRows(0);
            bks = bk.getListBKMonAnbyMAHD(Ma_HD);
            for (int i=0; i < bks.size(); i++)
               
                mode.addRow(new Object[]{bks.get(i).getMAMON(),bks.get(i).getMAHD(),bks.get(i).getNGAY(),bks.get(i).getSOLUONG(),bks.get(i).getTHANHTIEN()});
        }
        else
            JOptionPane.showMessageDialog(frame, "Không có dữ liệu để hiển thị");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XOA_BANGKE_MA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XOA_BANGKE_MA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XOA_BANGKE_MA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XOA_BANGKE_MA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XOA_BANGKE_MA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable jBKMA;
    private javax.swing.JButton jDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField jMAHD;
    private javax.swing.JTextField jMAMON;
    private javax.swing.JTextField jNgay;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jShow;
    private javax.swing.JTextField jSoLuong;
    private javax.swing.JTextField jTHANHTIEN;
    // End of variables declaration//GEN-END:variables
}
