/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.BANGKE_DV_BUS;
import DTO.BANGKE_DV_DTO;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.*;

/**
 *
 * @author ADMIN
 */
public class XOA_BANGKE_DV extends javax.swing.JFrame {

    /**
     * Creates new form BANGKE_DV
     */
    public XOA_BANGKE_DV() {
        initComponents();
    }
    
    int row = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTXOABK = new javax.swing.JTable();
        jDelete = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMaHD = new javax.swing.JTextField();
        jMaDV = new javax.swing.JTextField();
        jNgay = new javax.swing.JTextField();
        jThanhTien = new javax.swing.JTextField();
        jShow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(1, 50, 67));

        jTXOABK.setBackground(new java.awt.Color(247, 202, 24));
        jTXOABK.setForeground(new java.awt.Color(1, 50, 67));
        jTXOABK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", ""},
                {"", "", "", ""},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Dịch vụ", "Mã Hóa đơn", "Ngày sử dụng", "Thành tiền"
            }
        ));
        jTXOABK.setShowGrid(true);
        jTXOABK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTXOABKMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTXOABK);

        jDelete.setBackground(new java.awt.Color(247, 202, 24));
        jDelete.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jDelete.setForeground(new java.awt.Color(1, 50, 67));
        jDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_delete_20px.png"))); // NOI18N
        jDelete.setText("XÓA");
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(247, 202, 24));
        jLabel9.setText("XÓA BẢNG KÊ DỊCH VỤ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(247, 202, 24));
        jLabel4.setText("MÃ HÓA ĐƠN");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 202, 24));
        jLabel1.setText("DỊCH VỤ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(247, 202, 24));
        jLabel2.setText("NGÀY SỬ DỤNG");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(247, 202, 24));
        jLabel6.setText("THÀNH TIỀN");

        jMaHD.setEditable(false);

        jMaDV.setEditable(false);

        jNgay.setEditable(false);

        jThanhTien.setEditable(false);

        jShow.setBackground(new java.awt.Color(247, 202, 24));
        jShow.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jShow.setForeground(new java.awt.Color(1, 50, 67));
        jShow.setText("Hiển thị dữ liệu");
        jShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jNgay, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(jMaDV)
                            .addComponent(jMaHD)
                            .addComponent(jThanhTien)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jShow)
                        .addGap(18, 18, 18)
                        .addComponent(jDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(194, 194, 194))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addGap(92, 92, 92)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jShow, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ShowBangKeDV ()
    {
        List<BANGKE_DV_DTO> bks = new ArrayList<BANGKE_DV_DTO>();
        BANGKE_DV_BUS bk = new BANGKE_DV_BUS();
        Component frame = null;
        int Ma_HD = Integer.parseInt(jMaHD.getText());
        
        if(bk.getListBangKeDVbyMAHD(Ma_HD) != null)
        {
            javax.swing.table.DefaultTableModel mode;
            mode = (javax.swing.table.DefaultTableModel) this.jTXOABK.getModel();
            mode.setNumRows(0);
            bks = bk.getListBangKeDVbyMAHD(Ma_HD);
            for (int i=0; i < bks.size(); i++)
                mode.addRow(new Object[]{bks.get(i).getMADV(),bks.get(i).getMAHD(),bks.get(i).getNGAY(),bks.get(i).getTHANHTIEN()});
        }
        else
            JOptionPane.showMessageDialog(frame, "Không có dữ liệu để hiển thị");
    }
    private void jTXOABKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTXOABKMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTXOABK.getModel();
        row = jTXOABK.getSelectedRow();
        
        jMaDV.setText(model.getValueAt(row, 0).toString());
        jMaHD.setText(model.getValueAt(row, 1).toString());
        jNgay.setText(model.getValueAt(row, 2).toString());
        jThanhTien.setText(model.getValueAt(row, 3).toString());
    }//GEN-LAST:event_jTXOABKMouseClicked

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
        // TODO add your handling code here:
        BANGKE_DV_DTO bk = new BANGKE_DV_DTO();
        bk.setMADV(Integer.parseInt(jMaDV.getText()));
        bk.setMAHD(Integer.parseInt(jMaHD.getText()));
        bk.setNGAY(jNgay.getText());
        bk.setTHANHTIEN(Integer.parseInt(jThanhTien.getText()));
        
        Component frame = null;
        
        if(jMaDV.getText() != null)
        {
            BANGKE_DV_BUS bks = new BANGKE_DV_BUS();
            
            int buttonoption = JOptionPane.showConfirmDialog(frame,"Xác nhận xóa bảng kê dịch vụ ?");
            if(buttonoption == JOptionPane.YES_OPTION)
            {
                boolean rs = bks.DELETE_BANGKE_DV(bk);
                if(rs==true)
                {
                    JOptionPane.showMessageDialog(frame, "Xóa bảng kê dịch vụ thành công");
                    DefaultTableModel model = (DefaultTableModel)jTXOABK.getModel();
                    model.removeRow(row);
                }
                else
                    JOptionPane.showMessageDialog(frame, "Xóa bảng kê dịch vụ thất bại");
            }
            else
            {
                int button = JOptionPane.showConfirmDialog(frame, "Không tìm thấy bảng kê dịch vụ");
                if(button == JOptionPane.NO_OPTION)
                    System.exit(0);
            }
        }
        else
            JOptionPane.showMessageDialog(frame,"Vui lòng click chọn bảng kê dịch vụ muốn xóa!");
        
    }//GEN-LAST:event_jDeleteActionPerformed

    private void jShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowActionPerformed
        // TODO add your handling code here:
        ShowBangKeDV();
    }//GEN-LAST:event_jShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XOA_BANGKE_DV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XOA_BANGKE_DV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XOA_BANGKE_DV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XOA_BANGKE_DV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XOA_BANGKE_DV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jMaDV;
    public static javax.swing.JTextField jMaHD;
    private javax.swing.JTextField jNgay;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jShow;
    private javax.swing.JTable jTXOABK;
    private javax.swing.JTextField jThanhTien;
    // End of variables declaration//GEN-END:variables
}
